# Generated by Django 6.0.5 on 2026-09-20 06:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ngày cập nhật"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="tên tiện nghi"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="mô tả")),
            ],
            options={
                "verbose_name": "tiện nghi",
                "verbose_name_plural": "tiện nghi",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ngày cập nhật"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="mã hợp đồng"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(db_index=True, verbose_name="ngày bắt đầu"),
                ),
                (
                    "end_date",
                    models.DateField(db_index=True, verbose_name="ngày kết thúc"),
                ),
                (
                    "monthly_rent",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="giá thuê/tháng"
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="tiền cọc",
                    ),
                ),
                (
                    "billing_day",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="ngày lập hóa đơn"
                    ),
                ),
                (
                    "due_day",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="hạn thanh toán"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Bản nháp"),
                            ("active", "Đang hiệu lực"),
                            ("expired", "Hết hạn"),
                            ("terminated", "Đã chấm dứt"),
                            ("cancelled", "Đã hủy"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="trạng thái",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ghi chú")),
            ],
            options={
                "verbose_name": "hợp đồng",
                "verbose_name_plural": "hợp đồng",
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ngày cập nhật"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="tên tòa nhà")),
                ("address", models.TextField(verbose_name="địa chỉ")),
                ("description", models.TextField(blank=True, verbose_name="mô tả")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="đang hoạt động"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buildings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="chủ sở hữu",
                    ),
                ),
            ],
            options={
                "verbose_name": "tòa nhà",
                "verbose_name_plural": "tòa nhà",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ngày cập nhật"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="mã hóa đơn"
                    ),
                ),
                (
                    "period",
                    models.DateField(
                        db_index=True,
                        help_text="Dùng ngày đầu tiên của tháng",
                        verbose_name="kỳ hóa đơn",
                    ),
                ),
                ("issued_date", models.DateField(verbose_name="ngày phát hành")),
                (
                    "due_date",
                    models.DateField(db_index=True, verbose_name="hạn thanh toán"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="tiền trước điều chỉnh",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="giảm trừ",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="tổng tiền",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="đã thanh toán",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Bản nháp"),
                            ("issued", "Đã phát hành"),
                            ("partial", "Thanh toán một phần"),
                            ("paid", "Đã thanh toán"),
                            ("overdue", "Quá hạn"),
                            ("cancelled", "Đã hủy"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="trạng thái",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ghi chú")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="rentals.contract",
                        verbose_name="hợp đồng",
                    ),
                ),
            ],
            options={
                "verbose_name": "hóa đơn",
                "verbose_name_plural": "hóa đơn",
                "ordering": ("-period", "-issued_date"),
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ngày cập nhật"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="tiêu đề")),
                ("content", models.TextField(verbose_name="nội dung")),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="đã đọc"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="thời gian đọc"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="người nhận",
                    ),
                ),
            ],
            options={
                "verbose_name": "thông báo",
                "verbose_name_plural": "thông báo",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ngày cập nhật"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="số tiền"
                    ),
                ),
                ("paid_at", models.DateTimeField(verbose_name="thời gian thanh toán")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Tiền mặt"),
                            ("transfer", "Chuyển khoản"),
                            ("other", "Khác"),
                        ],
                        max_length=20,
                        verbose_name="phương thức",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="mã tham chiếu"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ghi chú")),
                ("is_void", models.BooleanField(default=False, verbose_name="đã hủy")),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="rentals.invoice",
                        verbose_name="hóa đơn",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "thanh toán",
                "verbose_name_plural": "thanh toán",
                "ordering": ("-paid_at",),
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ngày cập nhật"),
                ),
                (
                    "number",
                    models.CharField(max_length=50, verbose_name="số/tên phòng"),
                ),
                (
                    "floor",
                    models.PositiveSmallIntegerField(default=1, verbose_name="tầng"),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="diện tích (m²)",
                    ),
                ),
                (
                    "monthly_rent",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="giá thuê/tháng"
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="tiền cọc đề xuất",
                    ),
                ),
                (
                    "max_occupants",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="số người tối đa"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Còn trống"),
                            ("reserved", "Đã đặt"),
                            ("occupied", "Đang thuê"),
                            ("maintenance", "Bảo trì"),
                            ("inactive", "Ngừng sử dụng"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                        verbose_name="trạng thái",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="mô tả")),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rooms",
                        to="rentals.amenity",
                        verbose_name="tiện nghi",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rooms",
                        to="rentals.building",
                        verbose_name="tòa nhà",
                    ),
                ),
            ],
            options={
                "verbose_name": "phòng",
                "verbose_name_plural": "phòng",
                "ordering": ("building__name", "floor", "number"),
            },
        ),
        migrations.CreateModel(
            name="MeterReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ngày cập nhật"),
                ),
                (
                    "meter_type",
                    models.CharField(
                        choices=[("electricity", "Điện"), ("water", "Nước")],
                        max_length=20,
                        verbose_name="loại đồng hồ",
                    ),
                ),
                (
                    "period",
                    models.DateField(
                        help_text="Dùng ngày đầu tiên của tháng",
                        verbose_name="kỳ ghi chỉ số",
                    ),
                ),
                (
                    "previous_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="chỉ số đầu"
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="chỉ số cuối"
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="thời gian ghi"
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_meter_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meter_readings",
                        to="rentals.room",
                        verbose_name="phòng",
                    ),
                ),
            ],
            options={
                "verbose_name": "chỉ số điện nước",
                "verbose_name_plural": "chỉ số điện nước",
                "ordering": ("-period", "room"),
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="rentals.room",
                verbose_name="phòng",
            ),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ngày cập nhật"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="tên dịch vụ"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kwh", "kWh"),
                            ("m3", "m³"),
                            ("person", "Người"),
                            ("room", "Phòng"),
                            ("fixed", "Cố định"),
                        ],
                        max_length=20,
                        verbose_name="đơn vị",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="đơn giá"
                    ),
                ),
                (
                    "is_metered",
                    models.BooleanField(default=False, verbose_name="tính theo chỉ số"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="đang áp dụng"),
                ),
            ],
            options={
                "verbose_name": "dịch vụ",
                "verbose_name_plural": "dịch vụ",
                "ordering": ("name",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("unit_price__gte", 0)),
                        name="service_price_non_negative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ngày cập nhật"),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="nội dung"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=14,
                        verbose_name="số lượng",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="đơn giá"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="thành tiền"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="rentals.invoice",
                        verbose_name="hóa đơn",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_items",
                        to="rentals.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "chi tiết hóa đơn",
                "verbose_name_plural": "chi tiết hóa đơn",
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ngày cập nhật"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="họ và tên"),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="số điện thoại"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True, verbose_name="ngày sinh"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Nam"), ("female", "Nữ"), ("other", "Khác")],
                        max_length=10,
                        verbose_name="giới tính",
                    ),
                ),
                (
                    "identity_number",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="số CCCD/hộ chiếu"
                    ),
                ),
                (
                    "identity_issued_date",
                    models.DateField(blank=True, null=True, verbose_name="ngày cấp"),
                ),
                (
                    "permanent_address",
                    models.TextField(blank=True, verbose_name="địa chỉ thường trú"),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="liên hệ khẩn cấp"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="đang hoạt động"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "khách thuê",
                "verbose_name_plural": "khách thuê",
                "ordering": ("full_name",),
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ngày cập nhật"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="tiêu đề")),
                ("description", models.TextField(verbose_name="mô tả")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Thấp"),
                            ("medium", "Trung bình"),
                            ("high", "Cao"),
                            ("urgent", "Khẩn cấp"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="mức ưu tiên",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Mới"),
                            ("in_progress", "Đang xử lý"),
                            ("resolved", "Đã xử lý"),
                            ("closed", "Đã đóng"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="trạng thái",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="thời gian xử lý xong"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents",
                        to="rentals.room",
                        verbose_name="phòng",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_incidents",
                        to="rentals.tenant",
                        verbose_name="người báo",
                    ),
                ),
            ],
            options={
                "verbose_name": "sự cố",
                "verbose_name_plural": "sự cố",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ContractMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ngày cập nhật"),
                ),
                ("joined_date", models.DateField(verbose_name="ngày vào ở")),
                (
                    "left_date",
                    models.DateField(blank=True, null=True, verbose_name="ngày rời đi"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="rentals.contract",
                        verbose_name="hợp đồng",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_memberships",
                        to="rentals.tenant",
                        verbose_name="khách thuê",
                    ),
                ),
            ],
            options={
                "verbose_name": "thành viên hợp đồng",
                "verbose_name_plural": "thành viên hợp đồng",
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="representative",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="represented_contracts",
                to="rentals.tenant",
                verbose_name="người đại diện",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "cancelled"), _negated=True),
                fields=("contract", "period"),
                name="unique_active_invoice_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", 0)),
                name="invoice_subtotal_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount__gte", 0)),
                name="invoice_discount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)),
                name="invoice_total_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("paid_amount__gte", 0)),
                name="invoice_paid_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="payment_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("building", "number"), name="unique_room_number_per_building"
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.CheckConstraint(
                condition=models.Q(("monthly_rent__gte", 0)),
                name="room_rent_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.CheckConstraint(
                condition=models.Q(("deposit_amount__gte", 0)),
                name="room_deposit_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="meterreading",
            constraint=models.UniqueConstraint(
                fields=("room", "meter_type", "period"),
                name="unique_meter_reading_per_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="meterreading",
            constraint=models.CheckConstraint(
                condition=models.Q(("previous_value__gte", 0)),
                name="meter_previous_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="meterreading",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_value__gte", models.F("previous_value"))),
                name="meter_current_gte_previous",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)),
                name="invoice_item_quantity_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="invoice_item_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="invoice_item_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractmember",
            constraint=models.UniqueConstraint(
                fields=("contract", "tenant"), name="unique_tenant_per_contract"
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="contract_dates_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                condition=models.Q(("monthly_rent__gte", 0)),
                name="contract_rent_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                condition=models.Q(("deposit_amount__gte", 0)),
                name="contract_deposit_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                condition=models.Q(("billing_day__gte", 1), ("billing_day__lte", 28)),
                name="billing_day_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                condition=models.Q(("due_day__gte", 1), ("due_day__lte", 28)),
                name="due_day_valid",
            ),
        ),
    ]
