# Generated by Django 6.0.5 on 2026-09-21 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ngày cập nhật"),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Ảnh"), ("video", "Video")],
                        max_length=10,
                        verbose_name="loại",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        max_length=1000, verbose_name="đường dẫn Cloudinary"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        max_length=255, verbose_name="Cloudinary public ID"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="định dạng"
                    ),
                ),
                (
                    "bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="dung lượng"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="rentals.room",
                        verbose_name="phòng",
                    ),
                ),
            ],
            options={
                "verbose_name": "ảnh/video phòng",
                "verbose_name_plural": "ảnh/video phòng",
                "ordering": ("created_at",),
            },
        ),
    ]
