# Generated by Django 6.0.5 on 2026-09-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0002_roommedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="roommedia",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="ảnh chính"),
        ),
    ]
