# Generated from apps/rentals/templates.
TEMPLATES = {'base.html': '{% load static %}\n'
              '<!doctype html>\n'
              '<html lang="vi">\n'
              '<head>\n'
              '  <meta charset="utf-8">\n'
              '  <meta name="viewport" content="width=device-width, initial-scale=1">\n'
              '  <title>{% block title %}Quản lý phòng cho thuê{% endblock %}</title>\n'
              '  <link rel="stylesheet" href="{% static \'css/app.css\' %}">\n'
              '  <link rel="stylesheet" href="{% static \'css/pagination.css\' %}">\n'
              '  <link rel="stylesheet" href="{% static \'css/room-map.css\' %}">\n'
              '</head>\n'
              '<body>\n'
              '  <aside class="sidebar">\n'
              '    <a class="brand" href="{% if user.role == \'tenant\' %}{% url \'tenant-portal\' %}{% else %}{% url '
              '\'dashboard\' %}{% endif %}">QL Phòng Cho Thuê</a>\n'
              '    <nav>\n'
              "      {% if user.role == 'tenant' %}\n"
              '      <a href="{% url \'tenant-portal\' %}">Trang của tôi</a>\n'
              '      <a href="{% url \'tenant-contracts\' %}">Hợp đồng</a>\n'
              '      <a href="{% url \'tenant-invoices\' %}">Hóa đơn</a>\n'
              '      <a href="{% url \'tenant-incidents\' %}">Yêu cầu hỗ trợ</a>\n'
              '      <a href="{% url \'tenant-notifications\' %}">Thông báo</a>\n'
              '      {% else %}\n'
              '      <a href="{% url \'dashboard\' %}">Tổng quan</a>\n'
              '      <a href="{% url \'buildings\' %}">Tòa nhà</a>\n'
              '      <a href="{% url \'rooms\' %}">Phòng</a>\n'
              '      <a href="{% url \'room-map\' %}">Sơ đồ phòng</a>\n'
              '      <a href="{% url \'tenants\' %}">Khách thuê</a>\n'
              '      <a href="{% url \'contracts\' %}">Hợp đồng</a>\n'
              '      <a href="{% url \'meters\' %}">Điện nước</a>\n'
              '      <a href="{% url \'invoices\' %}">Hóa đơn</a>\n'
              '      <a href="{% url \'payments\' %}">Thanh toán</a>\n'
              '      <a href="{% url \'incidents\' %}">Sự cố</a>\n'
              '      {% if user.is_staff %}<a href="{% url \'admin:index\' %}">Quản trị</a>{% endif %}\n'
              '      {% endif %}\n'
              '    </nav>\n'
              '  </aside>\n'
              '  <main class="content">\n'
              '    <header class="topbar">\n'
              '      <div>{% block page_title %}Quản lý phòng cho thuê{% endblock %}</div>\n'
              '      <div class="userbox">\n'
              '        <span>{{ user.get_full_name|default:user.username }}</span>\n'
              '        <form method="post" action="{% url \'logout\' %}">{% csrf_token %}<button class="link-button" '
              'type="submit">Đăng xuất</button></form>\n'
              '      </div>\n'
              '    </header>\n'
              '    {% if messages %}{% for message in messages %}<div class="alert">{{ message }}</div>{% endfor %}{% '
              'endif %}\n'
              '    {% block content %}{% endblock %}\n'
              '  </main>\n'
              '  <script src="{% static \'lucide.min.js\' '
              '%}"></script><script>lucide.createIcons({attrs:{"stroke-width":2}});</script>\n'
              '</body>\n'
              '</html>\n',
 'public/base.html': '{% load static %}\n'
                     '<!doctype html>\n'
                     '<html lang="vi">\n'
                     '<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, '
                     'initial-scale=1"><title>{% block title %}Phòng cho thuê{% endblock %}</title><link '
                     'rel="stylesheet" href="{% static \'css/app.css\' %}"><link rel="stylesheet" href="{% static '
                     '\'css/public-home.css\' %}"><link rel="stylesheet" href="{% static \'css/lucide.css\' '
                     '%}"></head>\n'
                     '<body class="public-page">\n'
                     '  <header class="public-header">\n'
                     '    <a class="public-brand" href="{% url \'public-home\' %}"><span class="logo-mark"><i '
                     'data-lucide="house"></i></span><span><strong>Nhà Trọ An Tâm</strong><small>An cư để vững '
                     'bước</small></span></a>\n'
                     '    <nav><a class="active" href="{% url \'public-home\' %}"><i data-lucide="house"></i> Trang '
                     'chủ</a><a href="{% url \'public-rooms\' %}"><i data-lucide="search"></i> Tìm phòng</a><a '
                     'href="#gioi-thieu"><i data-lucide="building-2"></i> Về chúng tôi</a><a href="#lien-he"><i '
                     'data-lucide="phone"></i> Liên hệ</a></nav>\n'
                     '    {% if user.is_authenticated %}<a class="btn primary login-cta" href="{% url \'dashboard\' '
                     '%}"><i data-lucide="circle-user-round"></i> Vào hệ thống</a>{% else %}<a class="btn primary '
                     'login-cta" href="{% url \'login\' %}"><i data-lucide="circle-user-round"></i> Đăng nhập</a>{% '
                     'endif %}\n'
                     '  </header>\n'
                     '  <main>{% block content %}{% endblock %}</main>\n'
                     '  <footer id="lien-he" class="public-footer"><strong>Nhà Trọ An Tâm</strong><span>Nền tảng tìm '
                     'và quản lý phòng cho thuê minh bạch, thuận tiện.</span></footer>\n'
                     '  <script src="{% static \'lucide.min.js\' '
                     '%}"></script><script>lucide.createIcons({attrs:{"stroke-width":2}});</script>\n'
                     '</body>\n'
                     '</html>\n',
 'public/home.html': '{% extends "public/base.html" %}\n'
                     '{% block title %}Tìm phòng cho thuê{% endblock %}\n'
                     '{% block content %}\n'
                     '<section class="hero-shell">\n'
                     '  <div class="hero">\n'
                     '    <div class="hero-copy"><span class="eyebrow">TÌM PHÒNG DỄ DÀNG, AN TÂM Ở LÂU '
                     'DÀI</span><h1>Chọn một nơi ở<br><em>phù hợp với bạn</em></h1><p>Khám phá các phòng trọ còn '
                     'trống, giá thuê rõ ràng và tiện nghi đầy đủ trước khi liên hệ chủ nhà. Bắt đầu tìm nơi ở lý '
                     'tưởng ngay hôm nay!</p>\n'
                     '      <form class="hero-search" action="{% url \'public-rooms\' %}"><label><span '
                     'class="search-icon"><i data-lucide="map-pin"></i></span><span><small>Nhập khu vực, tòa nhà hoặc '
                     'số phòng</small><input name="q" placeholder="Ví dụ: Quận 1, Khu B, Tòa '
                     'A..."></span></label><label class="type-select"><span class="search-icon sliders"><i '
                     'data-lucide="sliders-horizontal"></i></span><span><small>Loại phòng</small><select '
                     'name="type"><option>Tất cả</option></select></span></label><button class="btn primary"><i '
                     'data-lucide="search"></i> Tìm phòng</button></form>\n'
                     '      <div class="popular"><strong>Tìm kiếm phổ biến:</strong><a href="{% url \'public-rooms\' '
                     '%}?q=trường">Gần trường ĐH</a><a href="{% url \'public-rooms\' %}?q=trung tâm">Gần trung '
                     'tâm</a><a href="{% url \'public-rooms\' %}">Có máy lạnh</a><a href="{% url \'public-rooms\' '
                     '%}?max_price=3000000">Dưới 3 triệu</a></div>\n'
                     '    </div>\n'
                     '    <div class="hero-photo"><div class="feature-card safety"><i><span '
                     'data-lucide="shield-check"></span></i><span><strong>An toàn, minh bạch</strong><small>Thông tin '
                     'rõ ràng</small></span></div><div class="feature-stack"><div class="feature-card"><i><span '
                     'data-lucide="house"></span></i><span><strong>Nhiều lựa chọn</strong><small>Phù hợp nhu '
                     'cầu</small></span></div><div class="feature-card green"><i><span '
                     'data-lucide="map-pin"></span></i><span><strong>Vị trí thuận tiện</strong><small>Gần trường, '
                     'trung tâm</small></span></div><div class="feature-card pink"><i><span '
                     'data-lucide="heart"></span></i><span><strong>Tiện nghi đầy đủ</strong><small>Ở lâu dài, an '
                     'tâm</small></span></div></div><div class="photo-slogan">Một nơi ở tốt<br>cho hành trình tốt '
                     'hơn!</div></div>\n'
                     '  </div>\n'
                     '  <div class="stats-banner"><div><i><span data-lucide="house"></span></i><span><strong>{{ '
                     'available_count }}+</strong><small>Phòng đang còn trống</small></span></div><div><i><span '
                     'data-lucide="users"></span></i><span><strong>{{ building_count }}+</strong><small>Khu nhà cho '
                     'thuê</small></span></div><div><i><span '
                     'data-lucide="map-pin"></span></i><span><strong>10+</strong><small>Khu vực, '
                     'quận/huyện</small></span></div><div><i><span '
                     'data-lucide="heart"></span></i><span><strong>98%</strong><small>Khách hàng hài '
                     'lòng</small></span></div></div>\n'
                     '</section>\n'
                     '<section id="gioi-thieu" class="public-section room-showcase"><div '
                     'class="section-heading"><div><span class="eyebrow">GỢI Ý CHO BẠN</span><h2>Phòng đang còn '
                     'trống</h2><p>Một số phòng phù hợp với nhu cầu của bạn</p></div><a href="{% url \'public-rooms\' '
                     '%}">Xem tất cả →</a></div><div class="room-grid">{% for room in featured_rooms %}{% include '
                     '\'public/room_card.html\' %}{% empty %}<div class="empty-state">Hiện chưa có phòng trống được '
                     'đăng.</div>{% endfor %}</div></section>\n'
                     '{% endblock %}\n',
 'public/room_card.html': '<article class="room-card"><a class="room-visual" href="{% url \'public-room-detail\' '
                          'room.id %}"><span class="availability">Còn trống</span></a><div class="room-body"><div '
                          'class="room-location">{{ room.building.name }} · Tầng {{ room.floor }}</div><h3><a href="{% '
                          'url \'public-room-detail\' room.id %}">Phòng {{ room.number }}</a></h3><p>{{ '
                          'room.building.address|truncatechars:65 }}</p><div class="room-meta"><span>{% if room.area '
                          '%}{{ room.area }} m²{% else %}Đang cập nhật{% endif %}</span><span>{{ room.max_occupants }} '
                          'người</span></div><div class="room-price"><strong>{{ room.monthly_rent|vnd }} '
                          'đ</strong><span>/ tháng</span></div></div></article>\n',
 'public/room_detail.html': '{% extends "public/base.html" %}{% block title %}Phòng {{ room.number }} - {{ '
                            'room.building.name }}{% endblock %}{% block content %}<section class="public-section '
                            'room-detail"><a class="back-link" href="{% url \'public-rooms\' %}">← Quay lại danh '
                            'sách</a><div class="room-detail-grid"><div '
                            'class="detail-visual"><span>🛏️</span></div><article class="detail-card"><span '
                            'class="availability">Còn trống</span><p class="room-location">{{ room.building.name }} · '
                            'Tầng {{ room.floor }}</p><h1>Phòng {{ room.number }}</h1><p class="detail-address">{{ '
                            'room.building.address }}</p><div class="price-large">{{ room.monthly_rent|vnd }} đ '
                            '<span>/ tháng</span></div><div class="detail-grid"><div><span>Diện tích</span><strong>{{ '
                            'room.area|default:"Chưa cập nhật" }}{% if room.area %} m²{% endif '
                            '%}</strong></div><div><span>Số người tối đa</span><strong>{{ room.max_occupants }} '
                            'người</strong></div><div><span>Tiền cọc</span><strong>{{ room.deposit_amount|vnd }} '
                            'đ</strong></div><div><span>Trạng thái</span><strong>{{ room.get_status_display '
                            '}}</strong></div></div><h2>Tiện nghi</h2><div class="amenity-list">{% for item in '
                            'room.amenities.all %}<span>{{ item.name }}</span>{% empty %}<span>Đang cập nhật</span>{% '
                            'endfor %}</div>{% if room.description %}<h2>Mô tả</h2><p>{{ room.description|linebreaksbr '
                            '}}</p>{% endif %}<div class="contact-box"><div><span>Liên hệ chủ nhà</span><strong>{{ '
                            'room.building.owner.get_full_name|default:room.building.owner.username '
                            '}}</strong></div>{% if room.building.owner.phone %}<a class="btn primary" href="tel:{{ '
                            'room.building.owner.phone }}">Gọi {{ room.building.owner.phone }}</a>{% else '
                            '%}<span>Thông tin liên hệ đang cập nhật</span>{% endif '
                            '%}</div></article></div></section>{% endblock %}\n',
 'public/room_list.html': '{% extends "public/base.html" %}{% block title %}Danh sách phòng cho thuê{% endblock %}{% '
                          'block content %}<section class="public-section"><div class="section-heading"><div><span '
                          'class="eyebrow">PHÒNG CHO THUÊ</span><h1>Tìm phòng phù hợp</h1></div></div><form '
                          'class="public-filter" method="get"><input name="q" value="{{ q }}" placeholder="Khu vực, '
                          'tòa nhà, số phòng"><input name="min_price" type="number" min="0" value="{{ min_price }}" '
                          'placeholder="Giá từ"><input name="max_price" type="number" min="0" value="{{ max_price }}" '
                          'placeholder="Giá đến"><button class="btn primary">Áp dụng</button></form><p '
                          'class="result-count">Tìm thấy {{ rooms|length }} phòng còn trống</p><div '
                          'class="room-grid">{% for room in rooms %}{% include \'public/room_card.html\' %}{% empty '
                          '%}<div class="empty-state">Không tìm thấy phòng phù hợp. Hãy thử thay đổi điều kiện tìm '
                          'kiếm.</div>{% endfor %}</div></section>{% endblock %}\n',
 'registration/login.html': '{% load static %}\n'
                            '<!doctype html>\n'
                            '<html lang="vi">\n'
                            '<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, '
                            'initial-scale=1"><title>Đăng nhập</title><link rel="stylesheet" href="{% static '
                            '\'css/app.css\' %}"></head>\n'
                            '<body class="login-page">\n'
                            '  <section class="login-card">\n'
                            '    <h1>Quản lý phòng cho thuê</h1>\n'
                            '    <p>Đăng nhập để tiếp tục</p>\n'
                            '    {% if form.errors %}<div class="error">Tên đăng nhập hoặc mật khẩu không '
                            'đúng.</div>{% endif %}\n'
                            '    <form method="post">\n'
                            '      {% csrf_token %}\n'
                            '      <label for="id_username">Tên đăng nhập</label>{{ form.username }}\n'
                            '      <label for="id_password">Mật khẩu</label>{{ form.password }}\n'
                            '      <button class="btn primary full" type="submit">Đăng nhập</button>\n'
                            '    </form>\n'
                            '  </section>\n'
                            '</body>\n'
                            '</html>\n',
 'rentals/_list_header.html': '<div class="page-actions"><form method="get" class="search"><input name="q" value="{{ q '
                              '}}" placeholder="Tìm kiếm..."><button class="btn" type="submit">Tìm</button></form>{% '
                              'if create_url %}<a class="btn primary" href="{% url create_url %}">Thêm mới</a>{% endif '
                              '%}</div>\n',
 'rentals/building_list.html': '{% extends "base.html" %}{% block page_title %}Tòa nhà{% endblock %}{% block content '
                               "%}{% with create_url='building-create' %}{% include 'rentals/_list_header.html' %}{% "
                               'endwith %}<section class="panel"><table><thead><tr><th>Tên</th><th>Địa chỉ</th><th>Chủ '
                               'sở hữu</th><th>Trạng thái</th></tr></thead><tbody>{% for x in objects %}<tr><td>{{ '
                               'x.name }}</td><td>{{ x.address }}</td><td>{{ x.owner }}</td><td>{{ '
                               'x.is_active|yesno:"Hoạt động,Ngừng" }}</td></tr>{% empty %}<tr><td colspan="4">Chưa có '
                               'dữ liệu.</td></tr>{% endfor %}</tbody></table></section>{% endblock %}\n',
 'rentals/contract_list.html': '{% extends "base.html" %}{% block page_title %}Hợp đồng{% endblock %}{% block content '
                               "%}{% with create_url='contract-create' %}{% include 'rentals/_list_header.html' %}{% "
                               'endwith %}<section class="panel"><table><thead><tr><th>Mã</th><th>Phòng</th><th>Đại '
                               'diện</th><th>Thời hạn</th><th>Giá thuê</th><th>Trạng thái</th></tr></thead><tbody>{% '
                               'for x in objects %}<tr><td>{{ x.code }}</td><td>{{ x.room }}</td><td>{{ '
                               'x.representative }}</td><td>{{ x.start_date|date:"d/m/Y" }} – {{ '
                               'x.end_date|date:"d/m/Y" }}</td><td>{{ x.monthly_rent|vnd }} đ</td><td><span '
                               'class="badge">{{ x.get_status_display }}</span></td></tr>{% empty %}<tr><td '
                               'colspan="6">Chưa có dữ liệu.</td></tr>{% endfor %}</tbody></table></section>{% '
                               'endblock %}\n',
 'rentals/dashboard.html': '{% extends "base.html" %}\n'
                           '{% block title %}Tổng quan{% endblock %}\n'
                           '{% block page_title %}Tổng quan{% endblock %}\n'
                           '{% block content %}\n'
                           '<section class="stats-grid">\n'
                           '  <article class="stat"><span>Tổng số phòng</span><strong>{{ room_count '
                           '}}</strong></article>\n'
                           '  <article class="stat success"><span>Phòng trống</span><strong>{{ available_count '
                           '}}</strong></article>\n'
                           '  <article class="stat info"><span>Đang thuê</span><strong>{{ occupied_count '
                           '}}</strong></article>\n'
                           '  <article class="stat warning"><span>Hợp đồng hiệu lực</span><strong>{{ '
                           'active_contract_count }}</strong></article>\n'
                           '  <article class="stat danger"><span>Tổng công nợ</span><strong>{{ unpaid_total|vnd }} '
                           'đ</strong></article>\n'
                           '  <article class="stat"><span>Sự cố cần xử lý</span><strong>{{ open_incident_count '
                           '}}</strong></article>\n'
                           '</section>\n'
                           '<section class="two-columns">\n'
                           '  <article class="panel"><h2>Hóa đơn gần đây</h2><div '
                           'class="table-wrap"><table><thead><tr><th>Mã</th><th>Phòng</th><th>Tổng tiền</th><th>Trạng '
                           'thái</th></tr></thead><tbody>{% for item in recent_invoices %}<tr><td>{{ item.code '
                           '}}</td><td>{{ item.contract.room }}</td><td>{{ item.total_amount|vnd }} đ</td><td><span '
                           'class="badge">{{ item.get_status_display }}</span></td></tr>{% empty %}<tr><td '
                           'colspan="4">Chưa có hóa đơn.</td></tr>{% endfor %}</tbody></table></div></article>\n'
                           '  <article class="panel"><h2>Hợp đồng sắp hết hạn</h2><div '
                           'class="table-wrap"><table><thead><tr><th>Mã</th><th>Khách thuê</th><th>Ngày hết '
                           'hạn</th></tr></thead><tbody>{% for item in expiring_contracts %}<tr><td>{{ item.code '
                           '}}</td><td>{{ item.representative }}</td><td>{{ item.end_date|date:"d/m/Y" }}</td></tr>{% '
                           'empty %}<tr><td colspan="3">Chưa có hợp đồng.</td></tr>{% endfor '
                           '%}</tbody></table></div></article>\n'
                           '</section>\n'
                           '{% endblock %}\n',
 'rentals/form.html': '{% extends "base.html" %}\n'
                      '{% block page_title %}{{ title }}{% endblock %}\n'
                      '{% block content %}<section class="panel form-panel"><h1>{{ title }}</h1><form method="post">{% '
                      'csrf_token %}{{ form.as_p }}<div class="actions"><button class="btn primary" type="submit">Lưu '
                      'dữ liệu</button><button class="btn" type="button" onclick="history.back()">Quay '
                      'lại</button></div></form></section>{% endblock %}\n',
 'rentals/incident_list.html': '{% extends "base.html" %}{% block page_title %}Sự cố{% endblock %}{% block content '
                               "%}{% include 'rentals/_list_header.html' %}<section "
                               'class="panel"><table><thead><tr><th>Tiêu đề</th><th>Phòng</th><th>Người báo</th><th>Ưu '
                               'tiên</th><th>Trạng thái</th><th>Ngày báo</th></tr></thead><tbody>{% for x in objects '
                               '%}<tr><td>{{ x.title }}</td><td>{{ x.room }}</td><td>{{ x.reported_by }}</td><td>{{ '
                               'x.get_priority_display }}</td><td><span class="badge">{{ x.get_status_display '
                               '}}</span></td><td>{{ x.created_at|date:"d/m/Y H:i" }}</td></tr>{% empty %}<tr><td '
                               'colspan="6">Chưa có dữ liệu.</td></tr>{% endfor %}</tbody></table></section>{% '
                               'endblock %}\n',
 'rentals/invoice_list.html': '{% extends "base.html" %}{% block page_title %}Hóa đơn{% endblock %}{% block content '
                              "%}{% include 'rentals/_list_header.html' %}<section "
                              'class="panel"><table><thead><tr><th>Mã</th><th>Hợp đồng</th><th>Kỳ</th><th>Tổng '
                              'tiền</th><th>Đã trả</th><th>Còn nợ</th><th>Trạng thái</th></tr></thead><tbody>{% for x '
                              'in objects %}<tr><td>{{ x.code }}</td><td>{{ x.contract }}</td><td>{{ '
                              'x.period|date:"m/Y" }}</td><td>{{ x.total_amount|vnd }} đ</td><td>{{ x.paid_amount|vnd '
                              '}} đ</td><td>{{ x.balance|vnd }} đ</td><td><span class="badge">{{ x.get_status_display '
                              '}}</span></td></tr>{% empty %}<tr><td colspan="7">Chưa có dữ liệu.</td></tr>{% endfor '
                              '%}</tbody></table></section>{% endblock %}\n',
 'rentals/meter_list.html': '{% extends "base.html" %}{% block page_title %}Chỉ số điện nước{% endblock %}{% block '
                            "content %}{% with create_url='meter-create' %}{% include 'rentals/_list_header.html' %}{% "
                            'endwith %}<section '
                            'class="panel"><table><thead><tr><th>Phòng</th><th>Loại</th><th>Kỳ</th><th>Chỉ số '
                            'đầu</th><th>Chỉ số cuối</th><th>Tiêu thụ</th></tr></thead><tbody>{% for x in objects '
                            '%}<tr><td>{{ x.room }}</td><td>{{ x.get_meter_type_display }}</td><td>{{ '
                            'x.period|date:"m/Y" }}</td><td>{{ x.previous_value }}</td><td>{{ x.current_value '
                            '}}</td><td>{{ x.consumption }}</td></tr>{% empty %}<tr><td colspan="6">Chưa có dữ '
                            'liệu.</td></tr>{% endfor %}</tbody></table></section>{% endblock %}\n',
 'rentals/payment_list.html': '{% extends "base.html" %}{% block page_title %}Thanh toán{% endblock %}{% block content '
                              "%}{% include 'rentals/_list_header.html' %}<section "
                              'class="panel"><table><thead><tr><th>Hóa đơn</th><th>Số tiền</th><th>Thời '
                              'gian</th><th>Phương thức</th><th>Tham chiếu</th></tr></thead><tbody>{% for x in objects '
                              '%}<tr><td>{{ x.invoice }}</td><td>{{ x.amount|vnd }} đ</td><td>{{ x.paid_at|date:"d/m/Y '
                              'H:i" }}</td><td>{{ x.get_method_display }}</td><td>{{ x.reference|default:"—" '
                              '}}</td></tr>{% empty %}<tr><td colspan="5">Chưa có dữ liệu.</td></tr>{% endfor '
                              '%}</tbody></table></section>{% endblock %}\n',
 'rentals/room_list.html': '{% extends "base.html" %}\n'
                           '{% block page_title %}Phòng{% endblock %}\n'
                           '{% block content %}\n'
                           '<div class="page-actions room-toolbar">\n'
                           '  <form method="get" class="room-filters">\n'
                           '    <input name="q" value="{{ q }}" placeholder="Tìm số phòng hoặc tòa nhà...">\n'
                           '    <select name="building">\n'
                           '      <option value="">Tất cả tòa nhà</option>\n'
                           '      {% for building in buildings %}<option value="{{ building.id }}" {% if '
                           "selected_building == building.id|stringformat:'s' %}selected{% endif %}>{{ building.name "
                           '}}</option>{% endfor %}\n'
                           '    </select>\n'
                           '    <button class="btn" type="submit">Lọc dữ liệu</button>\n'
                           '    {% if q or selected_building %}<a class="btn" href="{% url \'rooms\' %}">Xóa lọc</a>{% '
                           'endif %}\n'
                           '  </form>\n'
                           '  <a class="btn primary" href="{% url \'room-create\' %}">Thêm phòng</a>\n'
                           '</div>\n'
                           '<section class="panel">\n'
                           '  <div class="list-summary">Hiển thị {{ page_obj.start_index }}–{{ page_obj.end_index }} '
                           'trong tổng số <strong>{{ paginator.count }}</strong> phòng</div>\n'
                           '  <div class="table-wrap"><table><thead><tr><th>Phòng</th><th>Tòa '
                           'nhà</th><th>Tầng</th><th>Giá thuê</th><th>Trạng thái</th></tr></thead><tbody>{% for x in '
                           'objects %}<tr><td>{{ x.number }}</td><td>{{ x.building }}</td><td>{{ x.floor }}</td><td>{{ '
                           'x.monthly_rent|vnd }} đ</td><td><span class="badge">{{ x.get_status_display '
                           '}}</span></td></tr>{% empty %}<tr><td colspan="5">Không tìm thấy phòng phù '
                           'hợp.</td></tr>{% endfor %}</tbody></table></div>\n'
                           '</section>\n'
                           '{% if page_obj.has_other_pages %}<nav class="pagination" aria-label="Phân trang phòng">\n'
                           '  {% if page_obj.has_previous %}<a href="?page={{ page_obj.previous_page_number }}&q={{ '
                           'q|urlencode }}&building={{ selected_building }}">← Trước</a>{% else %}<span '
                           'class="disabled">← Trước</span>{% endif %}\n'
                           '  {% for page_number in paginator.page_range %}{% if page_number == page_obj.number '
                           '%}<span class="current">{{ page_number }}</span>{% elif page_number >= '
                           "page_obj.number|add:'-2' and page_number <= page_obj.number|add:'2' %}<a "
                           'href="?page={{ page_number }}&q={{ q|urlencode }}&building={{ selected_building }}">{{ '
                           'page_number }}</a>{% endif %}{% endfor %}\n'
                           '  {% if page_obj.has_next %}<a href="?page={{ page_obj.next_page_number }}&q={{ '
                           'q|urlencode }}&building={{ selected_building }}">Sau →</a>{% else %}<span '
                           'class="disabled">Sau →</span>{% endif %}\n'
                           '</nav>{% endif %}\n'
                           '{% endblock %}\n',
 'rentals/room_map.html': '{% extends "base.html" %}\n'
                          '{% block title %}Sơ đồ phòng{% endblock %}\n'
                          '{% block page_title %}Sơ đồ phòng{% endblock %}\n'
                          '{% block content %}\n'
                          '<div class="map-heading">\n'
                          '  <div class="map-title"><span class="map-title-icon"><i '
                          'data-lucide="building-2"></i></span><div><h1>Sơ đồ phòng</h1><p>Tổng quan trạng thái phòng '
                          'theo từng tòa nhà và tầng</p></div></div>\n'
                          '  <form method="get" class="map-filters">\n'
                          '    <a class="map-control" href="{% url \'room-map\' %}"><i data-lucide="refresh-cw"></i> '
                          'Tải mới</a>\n'
                          '    <label class="map-control"><i data-lucide="list-filter"></i><select name="status" '
                          'onchange="this.form.submit()"><option value="">Tất cả trạng thái</option>{% for value,label '
                          'in status_choices %}<option value="{{ value }}" {% if selected_status == value %}selected{% '
                          'endif %}>{{ label }}</option>{% endfor %}</select></label>\n'
                          '    <label class="map-control"><i data-lucide="building-2"></i><select name="building" '
                          'onchange="this.form.submit()"><option value="">Tất cả tòa nhà</option>{% for building in '
                          'all_buildings %}<option value="{{ building.id }}" {% if selected_building == '
                          "building.id|stringformat:'s' %}selected{% endif %}>{{ building.name }}</option>{% endfor "
                          '%}</select></label>\n'
                          '  </form>\n'
                          '</div>\n'
                          '\n'
                          '<section class="map-stats">\n'
                          '  <article class="map-stat available"><div><span>TRỐNG</span><strong>{{ stats.available '
                          '}}</strong><small>/ {{ stats.total }} phòng</small></div><i '
                          'data-lucide="circle-check"></i></article>\n'
                          '  <article class="map-stat occupied"><div><span>ĐANG THUÊ</span><strong>{{ stats.occupied '
                          '}}</strong><small>/ {{ stats.total }} phòng</small></div><i '
                          'data-lucide="house"></i></article>\n'
                          '  <article class="map-stat reserved"><div><span>ĐÃ ĐẶT</span><strong>{{ stats.reserved '
                          '}}</strong><small>/ {{ stats.total }} phòng</small></div><i '
                          'data-lucide="clock-3"></i></article>\n'
                          '  <article class="map-stat maintenance"><div><span>BẢO TRÌ</span><strong>{{ '
                          'stats.maintenance }}</strong><small>/ {{ stats.total }} phòng</small></div><i '
                          'data-lucide="wrench"></i></article>\n'
                          '</section>\n'
                          '<section class="amenity-summary"><span class="amenity-icon"><i '
                          'data-lucide="snowflake"></i></span><div><b>CÓ ĐIỀU HÒA</b><strong>{{ stats.air_conditioned '
                          '}}</strong><small>/ {{ stats.total }} phòng</small></div><div class="without-air"><b>KHÔNG '
                          'CÓ ĐIỀU HÒA</b><strong>{{ stats.without_air_conditioner }}</strong><small>/ {{ stats.total '
                          '}} phòng</small></div></section>\n'
                          '\n'
                          '<section class="building-maps">\n'
                          '{% for card in building_cards %}\n'
                          '  <article class="building-map">\n'
                          '    <header><div class="building-name"><span><i '
                          'data-lucide="building-2"></i></span><div><h2>{{ card.building.name }}</h2><small>{{ '
                          'card.total }} phòng · 5 tầng</small></div></div><div class="building-badges"><b '
                          'class="available">Trống {{ card.counts.available }}</b><b class="occupied">Đang thuê {{ '
                          'card.counts.occupied }}</b><b class="reserved">Đã đặt {{ card.counts.reserved }}</b><b '
                          'class="maintenance">Bảo trì {{ card.counts.maintenance }}</b></div></header>\n'
                          '    <div class="floor-list">\n'
                          '      {% for floor in card.floors %}<div class="floor-row"><div '
                          'class="floor-label"><span>TẦNG</span><strong>{{ floor.number }}</strong></div><div '
                          'class="floor-rooms">{% for room in floor.rooms %}<a href="{% url \'api-room-detail\' '
                          'room.id %}" class="map-room {{ room.status }}" title="{{ room }} — {{ room.monthly_rent|vnd '
                          '}} đ/tháng"><i data-lucide="door-open"></i><strong>{{ room.number }}</strong><small>{{ '
                          'room.get_status_display }}</small>{% if room.has_air_conditioner %}<span class="air"><i '
                          'data-lucide="snowflake"></i></span>{% endif %}</a>{% endfor %}</div></div>{% empty %}<div '
                          'class="map-empty">Không có phòng phù hợp với bộ lọc.</div>{% endfor %}\n'
                          '    </div>\n'
                          '  </article>\n'
                          '{% empty %}<div class="panel map-empty">Không tìm thấy tòa nhà phù hợp.</div>{% endfor %}\n'
                          '</section>\n'
                          '<div class="map-legend"><span><i class="dot available"></i> Phòng trống</span><span><i '
                          'class="dot occupied"></i> Đang thuê</span><span><i class="dot reserved"></i> Đã '
                          'đặt</span><span><i class="dot maintenance"></i> Bảo trì</span></div>\n'
                          '{% endblock %}\n',
 'rentals/tenant_list.html': '{% extends "base.html" %}{% block page_title %}Khách thuê{% endblock %}{% block content '
                             "%}{% with create_url='tenant-create' %}{% include 'rentals/_list_header.html' %}{% "
                             'endwith %}<section class="panel"><table><thead><tr><th>Họ tên</th><th>Điện '
                             'thoại</th><th>Email</th><th>CCCD/Hộ chiếu</th><th>Trạng thái</th></tr></thead><tbody>{% '
                             'for x in objects %}<tr><td>{{ x.full_name }}</td><td>{{ x.phone }}</td><td>{{ '
                             'x.email|default:"—" }}</td><td>{{ x.identity_number }}</td><td>{{ '
                             'x.is_active|yesno:"Hoạt động,Ngừng" }}</td></tr>{% empty %}<tr><td colspan="5">Chưa có '
                             'dữ liệu.</td></tr>{% endfor %}</tbody></table></section>{% endblock %}\n',
 'tenant/contracts.html': '{% extends "base.html" %}{% block page_title %}Hợp đồng của tôi{% endblock %}{% block '
                          'content %}<section class="panel"><table><thead><tr><th>Mã</th><th>Phòng</th><th>Tòa '
                          'nhà</th><th>Thời hạn</th><th>Tiền thuê</th><th>Trạng thái</th></tr></thead><tbody>{% for x '
                          'in objects %}<tr><td>{{ x.code }}</td><td>{{ x.room.number }}</td><td>{{ '
                          'x.room.building.name }}</td><td>{{ x.start_date|date:"d/m/Y" }} – {{ '
                          'x.end_date|date:"d/m/Y" }}</td><td>{{ x.monthly_rent|vnd }} đ</td><td><span '
                          'class="badge">{{ x.get_status_display }}</span></td></tr>{% empty %}<tr><td colspan="6">Bạn '
                          'chưa có hợp đồng.</td></tr>{% endfor %}</tbody></table></section>{% endblock %}\n',
 'tenant/incident_form.html': '{% extends "base.html" %}{% block page_title %}Gửi yêu cầu hỗ trợ{% endblock %}{% block '
                              'content %}<section class="panel form-panel"><h1>Báo sự cố trong phòng</h1><p '
                              'class="muted">Mô tả rõ tình trạng để bộ phận quản lý xử lý nhanh hơn.</p><form '
                              'method="post">{% csrf_token %}{{ form.as_p }}<div class="actions"><button class="btn '
                              'primary" type="submit">Gửi yêu cầu</button><a class="btn" href="{% url '
                              '\'tenant-incidents\' %}">Hủy</a></div></form></section>{% endblock %}\n',
 'tenant/incidents.html': '{% extends "base.html" %}{% block page_title %}Yêu cầu hỗ trợ{% endblock %}{% block content '
                          '%}<div class="page-actions"><span></span><a class="btn primary" href="{% url '
                          '\'tenant-incident-create\' %}">Gửi yêu cầu mới</a></div><section '
                          'class="panel"><table><thead><tr><th>Ngày gửi</th><th>Phòng</th><th>Nội dung</th><th>Ưu '
                          'tiên</th><th>Trạng thái</th><th>Người xử lý</th></tr></thead><tbody>{% for x in objects '
                          '%}<tr><td>{{ x.created_at|date:"d/m/Y H:i" }}</td><td>{{ x.room.number '
                          '}}</td><td><strong>{{ x.title }}</strong><br><span class="muted">{{ '
                          'x.description|truncatechars:80 }}</span></td><td>{{ x.get_priority_display }}</td><td><span '
                          'class="badge">{{ x.get_status_display }}</span></td><td>{{ x.assigned_to|default:"Chưa phân '
                          'công" }}</td></tr>{% empty %}<tr><td colspan="6">Bạn chưa gửi yêu cầu nào.</td></tr>{% '
                          'endfor %}</tbody></table></section>{% endblock %}\n',
 'tenant/invoice_detail.html': '{% extends "base.html" %}{% block page_title %}Hóa đơn {{ invoice.code }}{% endblock '
                               '%}{% block content %}<section class="panel invoice-sheet"><div '
                               'class="detail-grid"><div><span>Kỳ hóa đơn</span><strong>{{ invoice.period|date:"m/Y" '
                               '}}</strong></div><div><span>Phòng</span><strong>{{ invoice.contract.room '
                               '}}</strong></div><div><span>Ngày phát hành</span><strong>{{ '
                               'invoice.issued_date|date:"d/m/Y" }}</strong></div><div><span>Hạn thanh '
                               'toán</span><strong>{{ invoice.due_date|date:"d/m/Y" }}</strong></div></div><h2>Chi '
                               'tiết</h2><table><thead><tr><th>Nội dung</th><th>Số lượng</th><th>Đơn giá</th><th>Thành '
                               'tiền</th></tr></thead><tbody>{% for x in invoice.items.all %}<tr><td>{{ x.description '
                               '}}</td><td>{{ x.quantity }}</td><td>{{ x.unit_price|vnd }} đ</td><td>{{ x.amount|vnd '
                               '}} đ</td></tr>{% endfor %}</tbody><tfoot><tr><th colspan="3">Tổng cộng</th><th>{{ '
                               'invoice.total_amount|vnd }} đ</th></tr><tr><th colspan="3">Đã thanh toán</th><th>{{ '
                               'invoice.paid_amount|vnd }} đ</th></tr><tr><th colspan="3">Còn nợ</th><th>{{ '
                               'invoice.balance|vnd }} đ</th></tr></tfoot></table><h2>Lịch sử thanh '
                               'toán</h2><table><thead><tr><th>Thời gian</th><th>Số tiền</th><th>Phương '
                               'thức</th><th>Tham chiếu</th></tr></thead><tbody>{% for x in invoice.payments.all %}{% '
                               'if not x.is_void %}<tr><td>{{ x.paid_at|date:"d/m/Y H:i" }}</td><td>{{ x.amount|vnd }} '
                               'đ</td><td>{{ x.get_method_display }}</td><td>{{ x.reference|default:"—" }}</td></tr>{% '
                               'endif %}{% empty %}<tr><td colspan="4">Chưa có thanh toán.</td></tr>{% endfor '
                               '%}</tbody></table></section>{% endblock %}\n',
 'tenant/invoices.html': '{% extends "base.html" %}{% block page_title %}Hóa đơn của tôi{% endblock %}{% block content '
                         '%}<section class="panel"><table><thead><tr><th>Mã hóa '
                         'đơn</th><th>Kỳ</th><th>Phòng</th><th>Tổng tiền</th><th>Đã trả</th><th>Còn nợ</th><th>Trạng '
                         'thái</th></tr></thead><tbody>{% for x in objects %}<tr><td><a href="{% url '
                         '\'tenant-invoice-detail\' x.id %}">{{ x.code }}</a></td><td>{{ x.period|date:"m/Y" '
                         '}}</td><td>{{ x.contract.room.number }}</td><td>{{ x.total_amount|vnd }} đ</td><td>{{ '
                         'x.paid_amount|vnd }} đ</td><td>{{ x.balance|vnd }} đ</td><td><span class="badge">{{ '
                         'x.get_status_display }}</span></td></tr>{% empty %}<tr><td colspan="7">Bạn chưa có hóa '
                         'đơn.</td></tr>{% endfor %}</tbody></table></section>{% endblock %}\n',
 'tenant/notifications.html': '{% extends "base.html" %}{% block page_title %}Thông báo{% endblock %}{% block content '
                              '%}<section class="notification-list">{% for x in objects %}<article class="panel '
                              'notification"><div><h2>{{ x.title }}</h2><p>{{ x.content }}</p></div><time>{{ '
                              'x.created_at|date:"d/m/Y H:i" }}</time></article>{% empty %}<article class="panel">Bạn '
                              'chưa có thông báo.</article>{% endfor %}</section>{% endblock %}\n',
 'tenant/portal.html': '{% extends "base.html" %}\n'
                       '{% block title %}Trang người thuê{% endblock %}\n'
                       '{% block page_title %}Xin chào, {{ tenant.full_name }}{% endblock %}\n'
                       '{% block content %}\n'
                       '<section class="stats-grid">\n'
                       '  <article class="stat info"><span>Phòng hiện tại</span><strong>{% if active_contract %}{{ '
                       'active_contract.room.number }}{% else %}—{% endif %}</strong></article>\n'
                       '  <article class="stat"><span>Tòa nhà</span><strong class="small-value">{% if active_contract '
                       '%}{{ active_contract.room.building.name }}{% else %}Chưa có{% endif %}</strong></article>\n'
                       '  <article class="stat danger"><span>Tổng cần thanh toán</span><strong>{{ total_debt|vnd }} '
                       'đ</strong></article>\n'
                       '  <article class="stat warning"><span>Thông báo chưa đọc</span><strong>{{ unread_count '
                       '}}</strong></article>\n'
                       '</section>\n'
                       '{% if active_contract %}<section class="panel tenant-room"><h2>Thông tin thuê hiện '
                       'tại</h2><div class="detail-grid"><div><span>Mã hợp đồng</span><strong>{{ active_contract.code '
                       '}}</strong></div><div><span>Thời hạn</span><strong>{{ active_contract.start_date|date:"d/m/Y" '
                       '}} – {{ active_contract.end_date|date:"d/m/Y" }}</strong></div><div><span>Giá '
                       'thuê</span><strong>{{ active_contract.monthly_rent|vnd }} đ/tháng</strong></div><div><span>Địa '
                       'chỉ</span><strong>{{ active_contract.room.building.address }}</strong></div></div></section>{% '
                       'endif %}\n'
                       '<section class="two-columns">\n'
                       '  <article class="panel"><div class="panel-heading"><h2>Hóa đơn cần thanh toán</h2><a href="{% '
                       'url \'tenant-invoices\' %}">Xem tất cả</a></div><table><thead><tr><th>Kỳ</th><th>Còn '
                       'nợ</th><th>Hạn trả</th></tr></thead><tbody>{% for x in unpaid_invoices %}<tr><td><a href="{% '
                       'url \'tenant-invoice-detail\' x.id %}">{{ x.period|date:"m/Y" }}</a></td><td>{{ x.balance|vnd '
                       '}} đ</td><td>{{ x.due_date|date:"d/m/Y" }}</td></tr>{% empty %}<tr><td colspan="3">Không có '
                       'hóa đơn cần thanh toán.</td></tr>{% endfor %}</tbody></table></article>\n'
                       '  <article class="panel"><div class="panel-heading"><h2>Yêu cầu gần đây</h2><a class="btn '
                       'primary compact" href="{% url \'tenant-incident-create\' %}">Gửi yêu '
                       'cầu</a></div><table><thead><tr><th>Nội dung</th><th>Trạng thái</th></tr></thead><tbody>{% for '
                       'x in incidents %}<tr><td>{{ x.title }}</td><td><span class="badge">{{ x.get_status_display '
                       '}}</span></td></tr>{% empty %}<tr><td colspan="2">Chưa có yêu cầu.</td></tr>{% endfor '
                       '%}</tbody></table></article>\n'
                       '</section>\n'
                       '{% endblock %}\n'}
