# Generated from apps/rentals/templates for serverless deployments.
TEMPLATES = {'base.html': '{% load static %}\n'
              '<!doctype html>\n'
              '<html lang="vi">\n'
              '<head>\n'
              '  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">\n'
              '  <title>{% block title %}Quản lý phòng cho thuê{% endblock %}</title>\n'
              '  <link rel="stylesheet" href="{% static \'css/app.css\' %}"><link rel="stylesheet" href="{% static '
              '\'css/pagination.css\' %}"><link rel="stylesheet" href="{% static \'css/room-map.css\' %}"><link '
              'rel="stylesheet" href="{% static \'css/room-map-compact.css\' %}"><link rel="stylesheet" href="{% '
              'static \'css/navigation.css\' %}"><link rel="stylesheet" href="{% static \'css/management.css\' %}">\n'
              '</head>\n'
              '<body>\n'
              '  <aside class="sidebar">\n'
              '    <a class="brand" href="{% if user.role == \'tenant\' %}{% url \'tenant-portal\' %}{% else %}{% url '
              '\'dashboard\' %}{% endif %}"><span class="brand-icon"><i data-lucide="house"></i></span><span>QL Phòng '
              'Cho Thuê<small>Quản lý dễ dàng · Vận hành hiệu quả</small></span></a>\n'
              '    <nav>\n'
              "      {% if user.role == 'tenant' %}\n"
              '      <a class="{% if request.resolver_match.url_name == \'tenant-portal\' %}active{% endif %}" '
              'href="{% url \'tenant-portal\' %}"><i data-lucide="layout-dashboard"></i>Trang của tôi</a>\n'
              '      <a class="{% if request.resolver_match.url_name == \'tenant-contracts\' %}active{% endif %}" '
              'href="{% url \'tenant-contracts\' %}"><i data-lucide="file-text"></i>Hợp đồng</a>\n'
              '      <a class="{% if request.resolver_match.url_name == \'tenant-invoices\' or '
              'request.resolver_match.url_name == \'tenant-invoice-detail\' %}active{% endif %}" href="{% url '
              '\'tenant-invoices\' %}"><i data-lucide="receipt-text"></i>Hóa đơn</a>\n'
              '      <a class="{% if request.resolver_match.url_name == \'tenant-incidents\' or '
              'request.resolver_match.url_name == \'tenant-incident-create\' %}active{% endif %}" href="{% url '
              '\'tenant-incidents\' %}"><i data-lucide="triangle-alert"></i>Yêu cầu hỗ trợ</a>\n'
              '      <a class="{% if request.resolver_match.url_name == \'tenant-notifications\' %}active{% endif %}" '
              'href="{% url \'tenant-notifications\' %}"><i data-lucide="bell"></i>Thông báo</a>\n'
              '      {% else %}\n'
              '      <a class="{% if request.resolver_match.url_name == \'dashboard\' %}active{% endif %}" href="{% '
              'url \'dashboard\' %}"><i data-lucide="house"></i>Tổng quan</a>\n'
              '      <a class="{% if request.resolver_match.url_name == \'buildings\' or '
              "request.resolver_match.url_name == 'building-create' or request.resolver_match.url_name == "
              '\'building-update\' %}active{% endif %}" href="{% url \'buildings\' %}"><i '
              'data-lucide="building-2"></i>Tòa nhà</a>\n'
              '      <a class="{% if request.resolver_match.url_name == \'rooms\' or request.resolver_match.url_name '
              '== \'room-create\' %}active{% endif %}" href="{% url \'rooms\' %}"><i '
              'data-lucide="bed-double"></i>Phòng</a>\n'
              '      <a class="{% if request.resolver_match.url_name == \'room-map\' %}active{% endif %}" href="{% url '
              '\'room-map\' %}"><i data-lucide="map"></i>Sơ đồ phòng</a>\n'
              '      <a class="{% if request.resolver_match.url_name == \'tenants\' or request.resolver_match.url_name '
              '== \'tenant-create\' %}active{% endif %}" href="{% url \'tenants\' %}"><i data-lucide="users"></i>Khách '
              'thuê</a>\n'
              '      <a class="{% if request.resolver_match.url_name == \'contracts\' or '
              'request.resolver_match.url_name == \'contract-create\' %}active{% endif %}" href="{% url \'contracts\' '
              '%}"><i data-lucide="files"></i>Hợp đồng</a>\n'
              '      <a class="{% if request.resolver_match.url_name == \'meters\' or request.resolver_match.url_name '
              '== \'meter-create\' %}active{% endif %}" href="{% url \'meters\' %}"><i data-lucide="zap"></i>Điện '
              'nước</a>\n'
              '      <a class="{% if request.resolver_match.url_name == \'invoices\' %}active{% endif %}" href="{% url '
              '\'invoices\' %}"><i data-lucide="receipt-text"></i>Hóa đơn</a>\n'
              '      <a class="{% if request.resolver_match.url_name == \'payments\' %}active{% endif %}" href="{% url '
              '\'payments\' %}"><i data-lucide="wallet-cards"></i>Thanh toán</a>\n'
              '      <a class="{% if request.resolver_match.url_name == \'incidents\' %}active{% endif %}" href="{% '
              'url \'incidents\' %}"><i data-lucide="triangle-alert"></i>Sự cố</a>\n'
              '      {% if user.is_staff %}<a href="{% url \'admin:index\' %}"><i data-lucide="settings"></i>Quản '
              'trị</a>{% endif %}\n'
              '      {% endif %}\n'
              '    </nav>\n'
              '    <small class="sidebar-version">Version 1.0.0</small>\n'
              '  </aside>\n'
              '  <main class="content">\n'
              '    <header class="topbar"><div class="page-heading"><h1>{% block page_title %}Quản lý phòng cho thuê{% '
              'endblock %}</h1><p>{% block page_subtitle %}{% endblock %}</p></div><div class="userbox"><span '
              'class="notification-bell"><i data-lucide="bell"></i><b></b></span><span class="user-avatar">{{ '
              'user.username|first|upper }}</span><span class="user-name"><strong>{{ '
              'user.get_full_name|default:user.username }}</strong><small>{{ user.get_role_display '
              '}}</small></span><form method="post" action="{% url \'logout\' %}">{% csrf_token %}<button '
              'class="link-button" type="submit" title="Đăng xuất"><i '
              'data-lucide="log-out"></i></button></form></div></header>\n'
              "    {% with route=request.resolver_match.url_name %}{% if route != 'dashboard' and route != "
              '\'tenant-portal\' %}<nav class="breadcrumbs" aria-label="Điều hướng trang"><a href="{% if user.role == '
              '\'tenant\' %}{% url \'tenant-portal\' %}{% else %}{% url \'dashboard\' %}{% endif %}"><i '
              'data-lucide="house"></i>Trang chủ</a><i data-lucide="chevron-right"></i>\n'
              "      {% if route == 'buildings' or route == 'building-create' or route == 'building-update' %}{% if "
              'route != \'buildings\' %}<a href="{% url \'buildings\' %}">Tòa nhà</a><i '
              'data-lucide="chevron-right"></i><span>{% if route == \'building-create\' %}Thêm tòa nhà{% else %}Chỉnh '
              'sửa tòa nhà{% endif %}</span>{% else %}<span>Tòa nhà</span>{% endif %}\n'
              "      {% elif route == 'rooms' or route == 'room-create' %}{% if route == 'room-create' %}<a "
              'href="{% url \'rooms\' %}">Phòng</a><i data-lucide="chevron-right"></i><span>Thêm phòng</span>{% else '
              '%}<span>Phòng</span>{% endif %}\n'
              "      {% elif route == 'room-map' %}<span>Sơ đồ phòng</span>\n"
              "      {% elif route == 'tenants' or route == 'tenant-create' %}{% if route == 'tenant-create' %}<a "
              'href="{% url \'tenants\' %}">Khách thuê</a><i data-lucide="chevron-right"></i><span>Thêm khách '
              'thuê</span>{% else %}<span>Khách thuê</span>{% endif %}\n'
              "      {% elif route == 'contracts' or route == 'contract-create' or route == 'tenant-contracts' %}{% if "
              'route == \'contract-create\' %}<a href="{% url \'contracts\' %}">Hợp đồng</a><i '
              'data-lucide="chevron-right"></i><span>Thêm hợp đồng</span>{% else %}<span>Hợp đồng</span>{% endif %}\n'
              "      {% elif route == 'meters' or route == 'meter-create' %}{% if route == 'meter-create' %}<a "
              'href="{% url \'meters\' %}">Điện nước</a><i data-lucide="chevron-right"></i><span>Thêm chỉ số</span>{% '
              'else %}<span>Điện nước</span>{% endif %}\n'
              "      {% elif route == 'invoices' or route == 'tenant-invoices' or route == 'tenant-invoice-detail' "
              '%}<span>Hóa đơn</span>\n'
              "      {% elif route == 'payments' %}<span>Thanh toán</span>\n"
              "      {% elif route == 'incidents' or route == 'tenant-incidents' or route == 'tenant-incident-create' "
              '%}<span>Sự cố</span>\n'
              "      {% elif route == 'tenant-notifications' %}<span>Thông báo</span>{% endif %}\n"
              '    </nav>{% endif %}{% endwith %}\n'
              '    {% if messages %}{% for message in messages %}<div class="alert">{{ message }}</div>{% endfor %}{% '
              'endif %}{% block content %}{% endblock %}\n'
              '  </main>\n'
              '  <script src="{% static \'lucide.min.js\' '
              '%}"></script><script>lucide.createIcons({attrs:{"stroke-width":2}});</script>\n'
              '</body></html>\n',
 'public/base.html': '{% load static %}\n'
                     '<!doctype html>\n'
                     '<html lang="vi">\n'
                     '<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, '
                     'initial-scale=1"><title>{% block title %}Phòng cho thuê{% endblock %}</title><link '
                     'rel="stylesheet" href="{% static \'css/app.css\' %}"><link rel="stylesheet" href="{% static '
                     '\'css/public-home.css\' %}"><link rel="stylesheet" href="{% static \'css/lucide.css\' '
                     '%}"></head>\n'
                     '<body class="public-page">\n'
                     '  <header class="public-header">\n'
                     '    <a class="public-brand" href="{% url \'public-home\' %}"><span class="logo-mark"><i '
                     'data-lucide="house"></i></span><span><strong>Nhà Trọ An Tâm</strong><small>An cư để vững '
                     'bước</small></span></a>\n'
                     '    <nav><a class="active" href="{% url \'public-home\' %}"><i data-lucide="house"></i> Trang '
                     'chủ</a><a href="{% url \'public-rooms\' %}"><i data-lucide="search"></i> Tìm phòng</a><a '
                     'href="#gioi-thieu"><i data-lucide="building-2"></i> Về chúng tôi</a><a href="#lien-he"><i '
                     'data-lucide="phone"></i> Liên hệ</a></nav>\n'
                     '    <div class="header-actions"><a class="favorite-link" href="{% url \'public-rooms\' %}"><i '
                     'data-lucide="heart"></i> Yêu thích</a>{% if user.is_authenticated %}<a class="btn primary '
                     'login-cta" href="{% url \'dashboard\' %}"><i data-lucide="circle-user-round"></i> Vào hệ '
                     'thống</a>{% else %}<a class="btn primary login-cta" href="{% url \'login\' %}"><i '
                     'data-lucide="circle-user-round"></i> Đăng nhập</a>{% endif %}</div>\n'
                     '  </header>\n'
                     '  <main>{% block content %}{% endblock %}</main>\n'
                     '  <footer id="lien-he" class="public-footer"><strong>Nhà Trọ An Tâm</strong><span>Nền tảng tìm '
                     'và quản lý phòng cho thuê minh bạch, thuận tiện.</span></footer>\n'
                     '  <script src="{% static \'lucide.min.js\' '
                     '%}"></script><script>lucide.createIcons({attrs:{"stroke-width":2}});</script>\n'
                     '</body>\n'
                     '</html>\n',
 'public/home.html': '{% extends "public/base.html" %}\n'
                     '{% block title %}Tìm phòng trọ phù hợp{% endblock %}\n'
                     '{% block content %}\n'
                     '<section class="guest-hero">\n'
                     '  <div class="guest-hero-inner">\n'
                     '    <div class="guest-hero-copy"><h1>Tìm phòng trọ phù hợp<br>với cuộc sống của bạn</h1><p>Đa '
                     'dạng lựa chọn <b>•</b> Thông tin minh bạch <b>•</b> An tâm dài lâu</p></div>\n'
                     '    <div class="hero-assurance"><i data-lucide="shield-check"></i><span>Không chỉ là phòng '
                     'trọ<small>Mà là nơi để vững bước</small></span></div>\n'
                     '    <form class="guest-search" action="{% url \'public-rooms\' %}">\n'
                     '      <label><i data-lucide="map-pin"></i><input name="q" placeholder="Khu vực, quận huyện, địa '
                     'chỉ..."></label>\n'
                     '      <label><i data-lucide="building-2"></i><select name="building"><option value="">Chọn tòa '
                     'nhà</option>{% for building in buildings %}<option value="{{ building.name }}">{{ building.name '
                     '}}</option>{% endfor %}</select></label>\n'
                     '      <label class="price-range"><i data-lucide="circle-dollar-sign"></i><input name="min_price" '
                     'type="number" placeholder="Giá từ"><b>-</b><input name="max_price" type="number" '
                     'placeholder="Giá đến"></label>\n'
                     '      <label><i data-lucide="bed-double"></i><select><option>Loại phòng</option><option>Phòng '
                     'trọ</option><option>Căn hộ mini</option></select></label>\n'
                     '      <button class="btn primary"><i data-lucide="search"></i> Tìm phòng</button>\n'
                     '    </form>\n'
                     '  </div>\n'
                     '</section>\n'
                     '<section class="benefit-strip">\n'
                     '  <div><i data-lucide="house"></i><span><strong>Nhiều tòa nhà</strong><small>và vị trí thuận '
                     'tiện</small></span></div>\n'
                     '  <div><i data-lucide="shield-check"></i><span><strong>Thông tin rõ ràng</strong><small>hình ảnh '
                     'thực tế</small></span></div>\n'
                     '  <div><i data-lucide="heart"></i><span><strong>Dễ dàng so sánh</strong><small>và lưu phòng yêu '
                     'thích</small></span></div>\n'
                     '  <div><i data-lucide="headphones"></i><span><strong>Hỗ trợ nhanh chóng</strong><small>tận tình, '
                     'chuyên nghiệp</small></span></div>\n'
                     '</section>\n'
                     '<section id="gioi-thieu" class="property-browser">\n'
                     '  <aside class="filter-panel">\n'
                     '    <h2>Bộ lọc tìm kiếm</h2>\n'
                     '    <form action="{% url \'public-rooms\' %}">\n'
                     '      <h3>Khu vực</h3>\n'
                     '      <select name="q"><option value="">Chọn quận / huyện</option><option>Quận '
                     '3</option><option>Quận 10</option><option>Thủ Đức</option></select>\n'
                     '      <select><option>Chọn phường / xã</option></select>\n'
                     '      <h3>Tòa nhà</h3>\n'
                     '      {% for group in building_groups %}<label class="check-row"><input type="checkbox" '
                     'name="building" value="{{ group.building.name }}"><span>{{ group.building.name '
                     '}}</span><small>{{ group.available_count }}</small></label>{% endfor %}\n'
                     '      <h3>Khoảng giá</h3>\n'
                     '      <input class="range-control" type="range" min="0" max="10000000" step="500000" '
                     'value="7500000">\n'
                     '      <div class="range-label"><span>0 đ</span><span>10.000.000 đ+</span></div>\n'
                     '      <h3>Tiện ích</h3>\n'
                     '      <label class="check-row"><input type="checkbox"><span>Có máy lạnh</span></label>\n'
                     '      <label class="check-row"><input type="checkbox"><span>Có nội thất</span></label>\n'
                     '      <label class="check-row"><input type="checkbox"><span>WiFi miễn phí</span></label>\n'
                     '      <button class="btn primary mobile-filter-submit">Áp dụng bộ lọc</button>\n'
                     '    </form>\n'
                     '  </aside>\n'
                     '  <div class="building-results">\n'
                     '    <div class="results-heading"><div><h2>Danh sách tòa nhà</h2><p>Chọn tòa nhà để xem các phòng '
                     'bên trong</p></div><label>Sắp xếp <select><option>Mới nhất</option><option>Giá thấp '
                     'nhất</option></select></label></div>\n'
                     '    {% for group in building_groups %}\n'
                     '    <article class="building-block">\n'
                     '      <header>\n'
                     '        <div class="building-thumb building-thumb-{{ forloop.counter }}"></div>\n'
                     '        <div class="building-info"><h3>{{ group.building.name }} {% if forloop.first %}<span>Tòa '
                     'nhà nổi bật</span>{% endif %}</h3><p><i data-lucide="map-pin"></i> {{ group.building.address '
                     '}}</p><div><span><i data-lucide="building-2"></i> {{ group.floor_count }} tầng</span><span><i '
                     'data-lucide="bed-double"></i> {{ group.available_count }} phòng trống</span><span><i '
                     'data-lucide="map-pin"></i> Gần chợ, trường học, trung tâm</span></div></div>\n'
                     '        <a class="view-building" href="{% url \'public-rooms\' %}?q={{ '
                     'group.building.name|urlencode }}">Xem tất cả {{ group.available_count }} phòng <i '
                     'data-lucide="arrow-right"></i></a>\n'
                     '      </header>\n'
                     '      <div class="compact-room-grid">{% for room in group.rooms %}{% include '
                     '"public/room_card.html" %}{% endfor %}</div>\n'
                     '    </article>\n'
                     '    {% empty %}<div class="empty-state">Hiện chưa có phòng trống được đăng.</div>{% endfor %}\n'
                     '  </div>\n'
                     '</section>\n'
                     '{% endblock %}\n',
 'public/room_card.html': '<article class="room-card"><a class="room-visual" href="{% url \'public-room-detail\' '
                          'room.id %}"><button type="button" aria-label="Thêm vào yêu thích"><i '
                          'data-lucide="heart"></i></button></a><div class="room-body"><h3><a href="{% url '
                          '\'public-room-detail\' room.id %}">Phòng {{ room.number }}</a></h3><div '
                          'class="room-price"><strong>{{ room.monthly_rent|vnd }} đ/tháng</strong></div><div '
                          'class="room-meta"><span><i data-lucide="scan"></i> {% if room.area %}{{ room.area }}m²{% '
                          'else %}--{% endif %}</span><span><i data-lucide="bed-double"></i> {{ room.max_occupants }} '
                          'người</span></div><span class="availability">Còn trống</span></div></article>\n',
 'public/room_detail.html': '{% extends "public/base.html" %}{% block title %}Phòng {{ room.number }} - {{ '
                            'room.building.name }}{% endblock %}{% block content %}<section class="public-section '
                            'room-detail"><a class="back-link" href="{% url \'public-rooms\' %}">← Quay lại danh '
                            'sách</a><div class="room-detail-grid"><div '
                            'class="detail-visual"><span>🛏️</span></div><article class="detail-card"><span '
                            'class="availability">Còn trống</span><p class="room-location">{{ room.building.name }} · '
                            'Tầng {{ room.floor }}</p><h1>Phòng {{ room.number }}</h1><p class="detail-address">{{ '
                            'room.building.address }}</p><div class="price-large">{{ room.monthly_rent|vnd }} đ '
                            '<span>/ tháng</span></div><div class="detail-grid"><div><span>Diện tích</span><strong>{{ '
                            'room.area|default:"Chưa cập nhật" }}{% if room.area %} m²{% endif '
                            '%}</strong></div><div><span>Số người tối đa</span><strong>{{ room.max_occupants }} '
                            'người</strong></div><div><span>Tiền cọc</span><strong>{{ room.deposit_amount|vnd }} '
                            'đ</strong></div><div><span>Trạng thái</span><strong>{{ room.get_status_display '
                            '}}</strong></div></div><h2>Tiện nghi</h2><div class="amenity-list">{% for item in '
                            'room.amenities.all %}<span>{{ item.name }}</span>{% empty %}<span>Đang cập nhật</span>{% '
                            'endfor %}</div>{% if room.description %}<h2>Mô tả</h2><p>{{ room.description|linebreaksbr '
                            '}}</p>{% endif %}<div class="contact-box"><div><span>Liên hệ chủ nhà</span><strong>{{ '
                            'room.building.owner.get_full_name|default:room.building.owner.username '
                            '}}</strong></div>{% if room.building.owner.phone %}<a class="btn primary" href="tel:{{ '
                            'room.building.owner.phone }}">Gọi {{ room.building.owner.phone }}</a>{% else '
                            '%}<span>Thông tin liên hệ đang cập nhật</span>{% endif '
                            '%}</div></article></div></section>{% endblock %}\n',
 'public/room_list.html': '{% extends "public/base.html" %}{% block title %}Danh sách phòng cho thuê{% endblock %}{% '
                          'block content %}<section class="public-section"><div class="section-heading"><div><span '
                          'class="eyebrow">PHÒNG CHO THUÊ</span><h1>Tìm phòng phù hợp</h1></div></div><form '
                          'class="public-filter" method="get"><input name="q" value="{{ q }}" placeholder="Khu vực, '
                          'tòa nhà, số phòng"><input name="min_price" type="number" min="0" value="{{ min_price }}" '
                          'placeholder="Giá từ"><input name="max_price" type="number" min="0" value="{{ max_price }}" '
                          'placeholder="Giá đến"><button class="btn primary">Áp dụng</button></form><p '
                          'class="result-count">Tìm thấy {{ rooms|length }} phòng còn trống</p><div '
                          'class="room-grid">{% for room in rooms %}{% include \'public/room_card.html\' %}{% empty '
                          '%}<div class="empty-state">Không tìm thấy phòng phù hợp. Hãy thử thay đổi điều kiện tìm '
                          'kiếm.</div>{% endfor %}</div></section>{% endblock %}\n',
 'registration/login.html': '{% load static %}\n'
                            '<!doctype html>\n'
                            '<html lang="vi">\n'
                            '<head>\n'
                            '  <meta charset="utf-8">\n'
                            '  <meta name="viewport" content="width=device-width, initial-scale=1">\n'
                            '  <title>Đăng nhập | Nhà Trọ An Tâm</title>\n'
                            '  <link rel="stylesheet" href="{% static \'css/app.css\' %}">\n'
                            '  <link rel="stylesheet" href="{% static \'css/login.css\' %}">\n'
                            '  <link rel="stylesheet" href="{% static \'css/lucide.css\' %}">\n'
                            '</head>\n'
                            '<body class="auth-page">\n'
                            '  <main class="auth-shell">\n'
                            '    <section class="auth-visual" style="--login-image:url(\'{% static '
                            '\'images/anhlogin.png\' %}\')">\n'
                            '      <a class="auth-brand auth-brand-light" href="{% url \'public-home\' %}"><span><i '
                            'data-lucide="house"></i></span><div><strong>Nhà Trọ An Tâm</strong><small>An cư để vững '
                            'bước</small></div></a>\n'
                            '      <div class="visual-copy"><span class="visual-badge"><i '
                            'data-lucide="shield-check"></i> Không gian sống đáng tin cậy</span><h1>Một nơi ở '
                            'tốt<br>cho hành trình tốt hơn.</h1><p>Quản lý phòng thuê, hợp đồng và hóa đơn dễ dàng '
                            'trên cùng một hệ thống.</p></div>\n'
                            '      <div class="visual-stats"><span><strong>120+</strong><small>Phòng cho '
                            'thuê</small></span><span><strong>98%</strong><small>Khách hàng hài '
                            'lòng</small></span></div>\n'
                            '    </section>\n'
                            '    <section class="auth-panel">\n'
                            '      <a class="back-home" href="{% url \'public-home\' %}">Về trang chủ</a>\n'
                            '      <div class="auth-form-wrap">\n'
                            '        <a class="auth-brand auth-brand-mobile" href="{% url \'public-home\' %}"><span><i '
                            'data-lucide="house"></i></span><div><strong>Nhà Trọ An Tâm</strong><small>An cư để vững '
                            'bước</small></div></a>\n'
                            '        <div class="auth-heading"><span>CHÀO MỪNG TRỞ LẠI</span><h2>Đăng nhập tài '
                            'khoản</h2><p>Nhập thông tin của bạn để truy cập hệ thống quản lý.</p></div>\n'
                            '        {% if form.errors %}<div class="auth-error"><i '
                            'data-lucide="circle-alert"></i><span>Tên đăng nhập hoặc mật khẩu không '
                            'đúng.</span></div>{% endif %}\n'
                            '        <form method="post" class="auth-form">\n'
                            '          {% csrf_token %}\n'
                            '          {% if next %}<input type="hidden" name="next" value="{{ next }}">{% endif %}\n'
                            '          <label for="id_username">Tên đăng nhập</label>\n'
                            '          <div class="input-wrap"><i data-lucide="user"></i>{{ form.username }}</div>\n'
                            '          <div class="password-label"><label for="id_password">Mật khẩu</label><a '
                            'href="#">Quên mật khẩu?</a></div>\n'
                            '          <div class="input-wrap"><i data-lucide="lock-keyhole"></i>{{ form.password '
                            '}}<button id="toggle-password" type="button" aria-label="Hiện mật khẩu"><i '
                            'data-lucide="eye"></i></button></div>\n'
                            '          <label class="remember-row"><input type="checkbox" name="remember"><span>Ghi '
                            'nhớ đăng nhập</span></label>\n'
                            '          <button class="auth-submit" type="submit">Đăng nhập</button>\n'
                            '        </form>\n'
                            '        <p class="auth-help"><i data-lucide="headphones"></i> Cần hỗ trợ? <a '
                            'href="mailto:hotro@nhatroantam.vn">Liên hệ quản trị viên</a></p>\n'
                            '      </div>\n'
                            '      <p class="auth-copyright">© 2026 Nhà Trọ An Tâm. Mọi quyền được bảo lưu.</p>\n'
                            '    </section>\n'
                            '  </main>\n'
                            '  <script src="{% static \'lucide.min.js\' %}"></script>\n'
                            '  '
                            '<script>lucide.createIcons({attrs:{"stroke-width":2}});document.getElementById("toggle-password").addEventListener("click",function(){const '
                            'input=document.getElementById("id_password");input.type=input.type==="password"?"text":"password";this.innerHTML=input.type==="password"?\'<i '
                            'data-lucide="eye"></i>\':\'<i '
                            'data-lucide="eye-off"></i>\';lucide.createIcons({attrs:{"stroke-width":2}})});</script>\n'
                            '</body>\n'
                            '</html>\n',
 'rentals/_list_header.html': '<div class="page-actions"><form method="get" class="search"><input name="q" value="{{ q '
                              '}}" placeholder="Tìm kiếm..."><button class="btn" type="submit">Tìm</button></form>{% '
                              'if create_url %}<a class="btn primary" href="{% url create_url %}">Thêm mới</a>{% endif '
                              '%}</div>\n',
 'rentals/building_list.html': '{% extends "base.html" %}\n'
                               '{% block page_title %}Tòa nhà{% endblock %}\n'
                               '{% block page_subtitle %}Quản lý danh sách tòa nhà trong hệ thống{% endblock %}\n'
                               '{% block content %}\n'
                               '<section class="building-overview">\n'
                               '  <article class="overview-card total"><span><i '
                               'data-lucide="building-2"></i></span><strong>{{ building_total }}</strong><small>Tổng '
                               'số tòa nhà</small></article>\n'
                               '  <article class="overview-card active"><span><i '
                               'data-lucide="circle-check"></i></span><strong>{{ building_active '
                               '}}</strong><small>Đang hoạt động</small></article>\n'
                               '  <article class="overview-card paused"><span><i '
                               'data-lucide="pause"></i></span><strong>0</strong><small>Tạm ngừng</small></article>\n'
                               '  <article class="overview-card inactive"><span><i '
                               'data-lucide="circle-x"></i></span><strong>{{ building_inactive }}</strong><small>Ngừng '
                               'hoạt động</small></article>\n'
                               '  <div class="building-quote"><i data-lucide="building"></i><p>“Quản lý tòa '
                               'nhà<br>hiệu quả hơn mỗi ngày”</p></div>\n'
                               '</section>\n'
                               '<section class="building-panel building-card-panel">\n'
                               '  <header class="card-list-heading"><div><h2>Danh sách tòa nhà</h2><p>{{ '
                               'paginator.count }} tòa nhà được tìm thấy</p></div><a class="btn primary add-building" '
                               'href="{% url \'building-create\' %}"><i data-lucide="plus"></i>Thêm tòa '
                               'nhà</a></header>\n'
                               '  <form method="get" class="card-filter-bar">\n'
                               '    <label class="building-search"><i data-lucide="search"></i><input name="q" '
                               'value="{{ q }}" placeholder="Tìm kiếm theo tên, địa chỉ..."></label>\n'
                               '    <label class="select-field"><span>Trạng thái</span><select name="status" '
                               'onchange="this.form.submit()"><option value="">Tất cả</option><option value="active" '
                               "{% if status == 'active' %}selected{% endif %}>Hoạt động</option><option "
                               'value="inactive" {% if status == \'inactive\' %}selected{% endif %}>Ngừng hoạt '
                               'động</option></select></label>\n'
                               '    <label class="select-field"><span>Sắp xếp</span><select name="sort" '
                               'onchange="this.form.submit()"><option value="newest" {% if sort == \'newest\' '
                               '%}selected{% endif %}>Mới nhất</option><option value="name" {% if sort == \'name\' '
                               '%}selected{% endif %}>Tên A–Z</option></select></label>\n'
                               '    <button class="btn filter-button" type="submit">Tìm kiếm</button>\n'
                               '    <div class="view-switch"><span class="active"><i '
                               'data-lucide="layout-grid"></i></span><span><i data-lucide="list"></i></span></div>\n'
                               '  </form>\n'
                               '  <div class="building-card-grid">\n'
                               '    {% for x in objects %}<article class="property-card">\n'
                               '      <header><span class="select-box"></span><div><h3>{{ x.name }}</h3><p><i '
                               'data-lucide="map-pin"></i>{{ x.address|truncatechars:50 }}</p></div><div '
                               'class="card-actions"><a href="{% url \'public-rooms\' %}?building={{ x.name|urlencode '
                               '}}" title="Xem phòng"><i data-lucide="eye"></i></a><a href="{% url \'building-update\' '
                               'x.id %}" title="Chỉnh sửa"><i data-lucide="pencil"></i></a></div></header>\n'
                               '      <div class="room-counts"><span><strong>{{ x.total_rooms }}</strong><small>Tổng '
                               'phòng</small></span><span class="available"><strong>{{ x.available_rooms '
                               '}}</strong><small>Trống</small></span><span class="occupied"><strong>{{ '
                               'x.occupied_rooms }}</strong><small>Đang thuê</small></span></div>\n'
                               '      <div class="occupancy"><div><span>Lấp đầy</span><strong>{{ x.occupancy_percent '
                               '}}%</strong></div><progress max="100" value="{{ x.occupancy_percent '
                               '}}"></progress></div>\n'
                               '      <div class="amenity-tags">{% for name in x.amenity_tags %}<span>{{ name '
                               '}}</span>{% empty %}<span>Đang cập nhật tiện ích</span>{% endfor %}{% if '
                               'x.amenity_extra %}<span>+{{ x.amenity_extra }}</span>{% endif %}</div>\n'
                               '      <footer><span>Tạo lúc {{ x.created_at|date:"d/m/Y" }}</span>{% if x.is_active '
                               '%}<span class="status-dot active">Hoạt động</span>{% else %}<span class="status-dot '
                               'inactive">Ngừng hoạt động</span>{% endif %}</footer>\n'
                               '    </article>{% empty %}<div class="empty-state">Không tìm thấy tòa nhà phù '
                               'hợp.</div>{% endfor %}\n'
                               '  </div>\n'
                               '  <footer class="building-footer"><span>Hiển thị {{ page_obj.start_index }}–{{ '
                               'page_obj.end_index }} của {{ paginator.count }} tòa nhà</span>{% if '
                               'page_obj.has_other_pages %}<nav class="pagination">{% if page_obj.has_previous %}<a '
                               'href="?page={{ page_obj.previous_page_number }}&q={{ q|urlencode }}&status={{ status '
                               '}}&sort={{ sort }}">←</a>{% endif %}<span class="current">{{ page_obj.number '
                               '}}</span>{% if page_obj.has_next %}<a href="?page={{ page_obj.next_page_number }}&q={{ '
                               'q|urlencode }}&status={{ status }}&sort={{ sort }}">→</a>{% endif %}</nav>{% endif '
                               '%}</footer>\n'
                               '</section>\n'
                               '{% endblock %}\n',
 'rentals/contract_list.html': '{% extends "base.html" %}{% block page_title %}Hợp đồng{% endblock %}{% block content '
                               "%}{% with create_url='contract-create' %}{% include 'rentals/_list_header.html' %}{% "
                               'endwith %}<section class="panel"><div class="list-summary"><span>Danh sách hợp '
                               'đồng</span><span>Tổng số: <strong>{{ paginator.count '
                               '}}</strong></span></div><table><thead><tr><th '
                               'class="row-number">STT</th><th>Mã</th><th>Phòng</th><th>Đại diện</th><th>Thời '
                               'hạn</th><th>Giá thuê</th><th>Trạng thái</th></tr></thead><tbody>{% for x in objects '
                               '%}<tr><td class="row-number">{{ page_obj.start_index|add:forloop.counter0 '
                               '}}</td><td>{{ x.code }}</td><td>{{ x.room }}</td><td>{{ x.representative }}</td><td>{{ '
                               'x.start_date|date:"d/m/Y" }} – {{ x.end_date|date:"d/m/Y" }}</td><td>{{ '
                               'x.monthly_rent|vnd }} đ</td><td><span class="badge">{{ x.get_status_display '
                               '}}</span></td></tr>{% empty %}<tr><td colspan="7">Chưa có dữ liệu.</td></tr>{% endfor '
                               '%}</tbody></table></section>{% endblock %}\n',
 'rentals/dashboard.html': '{% extends "base.html" %}\n'
                           '{% block title %}Tổng quan{% endblock %}\n'
                           '{% block page_title %}Tổng quan{% endblock %}\n'
                           '{% block content %}\n'
                           '<section class="stats-grid">\n'
                           '  <article class="stat"><span>Tổng số phòng</span><strong>{{ room_count '
                           '}}</strong></article>\n'
                           '  <article class="stat success"><span>Phòng trống</span><strong>{{ available_count '
                           '}}</strong></article>\n'
                           '  <article class="stat info"><span>Đang thuê</span><strong>{{ occupied_count '
                           '}}</strong></article>\n'
                           '  <article class="stat warning"><span>Hợp đồng hiệu lực</span><strong>{{ '
                           'active_contract_count }}</strong></article>\n'
                           '  <article class="stat danger"><span>Tổng công nợ</span><strong>{{ unpaid_total|vnd }} '
                           'đ</strong></article>\n'
                           '  <article class="stat"><span>Sự cố cần xử lý</span><strong>{{ open_incident_count '
                           '}}</strong></article>\n'
                           '</section>\n'
                           '<section class="two-columns">\n'
                           '  <article class="panel"><h2>Hóa đơn gần đây</h2><div '
                           'class="table-wrap"><table><thead><tr><th>Mã</th><th>Phòng</th><th>Tổng tiền</th><th>Trạng '
                           'thái</th></tr></thead><tbody>{% for item in recent_invoices %}<tr><td>{{ item.code '
                           '}}</td><td>{{ item.contract.room }}</td><td>{{ item.total_amount|vnd }} đ</td><td><span '
                           'class="badge">{{ item.get_status_display }}</span></td></tr>{% empty %}<tr><td '
                           'colspan="4">Chưa có hóa đơn.</td></tr>{% endfor %}</tbody></table></div></article>\n'
                           '  <article class="panel"><h2>Hợp đồng sắp hết hạn</h2><div '
                           'class="table-wrap"><table><thead><tr><th>Mã</th><th>Khách thuê</th><th>Ngày hết '
                           'hạn</th></tr></thead><tbody>{% for item in expiring_contracts %}<tr><td>{{ item.code '
                           '}}</td><td>{{ item.representative }}</td><td>{{ item.end_date|date:"d/m/Y" }}</td></tr>{% '
                           'empty %}<tr><td colspan="3">Chưa có hợp đồng.</td></tr>{% endfor '
                           '%}</tbody></table></div></article>\n'
                           '</section>\n'
                           '{% endblock %}\n',
 'rentals/form.html': '{% extends "base.html" %}\n'
                      '{% block page_title %}{{ title }}{% endblock %}\n'
                      '{% block content %}<section class="panel form-panel"><h1>{{ title }}</h1><form method="post">{% '
                      'csrf_token %}{{ form.as_p }}<div class="actions"><button class="btn primary" type="submit">Lưu '
                      'dữ liệu</button><button class="btn" type="button" onclick="history.back()">Quay '
                      'lại</button></div></form></section>{% endblock %}\n',
 'rentals/incident_list.html': '{% extends "base.html" %}{% block page_title %}Sự cố{% endblock %}{% block content '
                               '%}{% include \'rentals/_list_header.html\' %}<section class="panel"><div '
                               'class="list-summary"><span>Danh sách sự cố</span><span>Tổng số: <strong>{{ '
                               'paginator.count }}</strong></span></div><table><thead><tr><th '
                               'class="row-number">STT</th><th>Tiêu đề</th><th>Phòng</th><th>Người báo</th><th>Ưu '
                               'tiên</th><th>Trạng thái</th><th>Ngày báo</th></tr></thead><tbody>{% for x in objects '
                               '%}<tr><td class="row-number">{{ page_obj.start_index|add:forloop.counter0 '
                               '}}</td><td>{{ x.title }}</td><td>{{ x.room }}</td><td>{{ x.reported_by }}</td><td>{{ '
                               'x.get_priority_display }}</td><td><span class="badge">{{ x.get_status_display '
                               '}}</span></td><td>{{ x.created_at|date:"d/m/Y H:i" }}</td></tr>{% empty %}<tr><td '
                               'colspan="7">Chưa có dữ liệu.</td></tr>{% endfor %}</tbody></table></section>{% '
                               'endblock %}\n',
 'rentals/invoice_list.html': '{% extends "base.html" %}{% block page_title %}Hóa đơn{% endblock %}{% block content '
                              '%}{% include \'rentals/_list_header.html\' %}<section class="panel"><div '
                              'class="list-summary"><span>Danh sách hóa đơn</span><span>Tổng số: <strong>{{ '
                              'paginator.count }}</strong></span></div><table><thead><tr><th '
                              'class="row-number">STT</th><th>Mã</th><th>Hợp đồng</th><th>Kỳ</th><th>Tổng '
                              'tiền</th><th>Đã trả</th><th>Còn nợ</th><th>Trạng thái</th></tr></thead><tbody>{% for x '
                              'in objects %}<tr><td class="row-number">{{ page_obj.start_index|add:forloop.counter0 '
                              '}}</td><td>{{ x.code }}</td><td>{{ x.contract }}</td><td>{{ x.period|date:"m/Y" '
                              '}}</td><td>{{ x.total_amount|vnd }} đ</td><td>{{ x.paid_amount|vnd }} đ</td><td>{{ '
                              'x.balance|vnd }} đ</td><td><span class="badge">{{ x.get_status_display '
                              '}}</span></td></tr>{% empty %}<tr><td colspan="8">Chưa có dữ liệu.</td></tr>{% endfor '
                              '%}</tbody></table></section>{% endblock %}\n',
 'rentals/meter_list.html': '{% extends "base.html" %}{% block page_title %}Chỉ số điện nước{% endblock %}{% block '
                            "content %}{% with create_url='meter-create' %}{% include 'rentals/_list_header.html' %}{% "
                            'endwith %}<section class="panel"><div class="list-summary"><span>Danh sách chỉ số điện '
                            'nước</span><span>Tổng số: <strong>{{ paginator.count '
                            '}}</strong></span></div><table><thead><tr><th '
                            'class="row-number">STT</th><th>Phòng</th><th>Loại</th><th>Kỳ</th><th>Chỉ số '
                            'đầu</th><th>Chỉ số cuối</th><th>Tiêu thụ</th></tr></thead><tbody>{% for x in objects '
                            '%}<tr><td class="row-number">{{ page_obj.start_index|add:forloop.counter0 }}</td><td>{{ '
                            'x.room }}</td><td>{{ x.get_meter_type_display }}</td><td>{{ x.period|date:"m/Y" '
                            '}}</td><td>{{ x.previous_value }}</td><td>{{ x.current_value }}</td><td>{{ x.consumption '
                            '}}</td></tr>{% empty %}<tr><td colspan="7">Chưa có dữ liệu.</td></tr>{% endfor '
                            '%}</tbody></table></section>{% endblock %}\n',
 'rentals/payment_list.html': '{% extends "base.html" %}{% block page_title %}Thanh toán{% endblock %}{% block content '
                              '%}{% include \'rentals/_list_header.html\' %}<section class="panel"><div '
                              'class="list-summary"><span>Danh sách thanh toán</span><span>Tổng số: <strong>{{ '
                              'paginator.count }}</strong></span></div><table><thead><tr><th '
                              'class="row-number">STT</th><th>Hóa đơn</th><th>Số tiền</th><th>Thời gian</th><th>Phương '
                              'thức</th><th>Tham chiếu</th></tr></thead><tbody>{% for x in objects %}<tr><td '
                              'class="row-number">{{ page_obj.start_index|add:forloop.counter0 }}</td><td>{{ x.invoice '
                              '}}</td><td>{{ x.amount|vnd }} đ</td><td>{{ x.paid_at|date:"d/m/Y H:i" }}</td><td>{{ '
                              'x.get_method_display }}</td><td>{{ x.reference|default:"—" }}</td></tr>{% empty '
                              '%}<tr><td colspan="6">Chưa có dữ liệu.</td></tr>{% endfor '
                              '%}</tbody></table></section>{% endblock %}\n',
 'rentals/room_list.html': '{% extends "base.html" %}\n'
                           '{% block page_title %}Phòng{% endblock %}\n'
                           '{% block content %}\n'
                           '<div class="page-actions room-toolbar">\n'
                           '  <form method="get" class="room-filters">\n'
                           '    <input name="q" value="{{ q }}" placeholder="Tìm số phòng hoặc tòa nhà...">\n'
                           '    <select name="building">\n'
                           '      <option value="">Tất cả tòa nhà</option>\n'
                           '      {% for building in buildings %}<option value="{{ building.id }}" {% if '
                           "selected_building == building.id|stringformat:'s' %}selected{% endif %}>{{ building.name "
                           '}}</option>{% endfor %}\n'
                           '    </select>\n'
                           '    <button class="btn" type="submit">Lọc dữ liệu</button>\n'
                           '    {% if q or selected_building %}<a class="btn" href="{% url \'rooms\' %}">Xóa lọc</a>{% '
                           'endif %}\n'
                           '  </form>\n'
                           '  <a class="btn primary" href="{% url \'room-create\' %}">Thêm phòng</a>\n'
                           '</div>\n'
                           '<section class="panel">\n'
                           '  <div class="list-summary">Hiển thị {{ page_obj.start_index }}–{{ page_obj.end_index }} '
                           'trong tổng số <strong>{{ paginator.count }}</strong> phòng</div>\n'
                           '  <div class="table-wrap"><table><thead><tr><th '
                           'class="row-number">STT</th><th>Phòng</th><th>Tòa nhà</th><th>Tầng</th><th>Giá '
                           'thuê</th><th>Trạng thái</th></tr></thead><tbody>{% for x in objects %}<tr><td '
                           'class="row-number">{{ page_obj.start_index|add:forloop.counter0 }}</td><td>{{ x.number '
                           '}}</td><td>{{ x.building }}</td><td>{{ x.floor }}</td><td>{{ x.monthly_rent|vnd }} '
                           'đ</td><td><span class="badge">{{ x.get_status_display }}</span></td></tr>{% empty '
                           '%}<tr><td colspan="6">Không tìm thấy phòng phù hợp.</td></tr>{% endfor '
                           '%}</tbody></table></div>\n'
                           '</section>\n'
                           '{% if page_obj.has_other_pages %}<nav class="pagination" aria-label="Phân trang phòng">\n'
                           '  {% if page_obj.has_previous %}<a href="?page={{ page_obj.previous_page_number }}&q={{ '
                           'q|urlencode }}&building={{ selected_building }}">← Trước</a>{% else %}<span '
                           'class="disabled">← Trước</span>{% endif %}\n'
                           '  {% for page_number in paginator.page_range %}{% if page_number == page_obj.number '
                           '%}<span class="current">{{ page_number }}</span>{% elif page_number >= '
                           "page_obj.number|add:'-2' and page_number <= page_obj.number|add:'2' %}<a "
                           'href="?page={{ page_number }}&q={{ q|urlencode }}&building={{ selected_building }}">{{ '
                           'page_number }}</a>{% endif %}{% endfor %}\n'
                           '  {% if page_obj.has_next %}<a href="?page={{ page_obj.next_page_number }}&q={{ '
                           'q|urlencode }}&building={{ selected_building }}">Sau →</a>{% else %}<span '
                           'class="disabled">Sau →</span>{% endif %}\n'
                           '</nav>{% endif %}\n'
                           '{% endblock %}\n',
 'rentals/room_map.html': '{% extends "base.html" %}\n'
                          '{% block title %}Sơ đồ phòng{% endblock %}\n'
                          '{% block page_title %}Sơ đồ phòng{% endblock %}\n'
                          '{% block page_subtitle %}Tổng quan trạng thái phòng theo từng tòa nhà và tầng{% endblock '
                          '%}\n'
                          '{% block content %}\n'
                          '<div class="map-heading">\n'
                          '  <form method="get" class="map-filters">\n'
                          '    <a class="map-control" href="{% url \'room-map\' %}"><i data-lucide="refresh-cw"></i> '
                          'Tải mới</a>\n'
                          '    <label class="map-control"><i data-lucide="list-filter"></i><select name="status" '
                          'onchange="this.form.submit()"><option value="">Tất cả trạng thái</option>{% for value,label '
                          'in status_choices %}<option value="{{ value }}" {% if selected_status == value %}selected{% '
                          'endif %}>{{ label }}</option>{% endfor %}</select></label>\n'
                          '    <label class="map-control"><i data-lucide="building-2"></i><select name="building" '
                          'onchange="this.form.submit()"><option value="">Tất cả tòa nhà</option>{% for building in '
                          'all_buildings %}<option value="{{ building.id }}" {% if selected_building == '
                          "building.id|stringformat:'s' %}selected{% endif %}>{{ building.name }}</option>{% endfor "
                          '%}</select></label>\n'
                          '  </form>\n'
                          '</div>\n'
                          '\n'
                          '<section class="map-stats">\n'
                          '  <article class="map-stat available"><div><span>TRỐNG</span><strong>{{ stats.available '
                          '}}</strong><small>/ {{ stats.total }} phòng</small></div><i '
                          'data-lucide="circle-check"></i></article>\n'
                          '  <article class="map-stat occupied"><div><span>ĐANG THUÊ</span><strong>{{ stats.occupied '
                          '}}</strong><small>/ {{ stats.total }} phòng</small></div><i '
                          'data-lucide="house"></i></article>\n'
                          '  <article class="map-stat reserved"><div><span>ĐÃ ĐẶT</span><strong>{{ stats.reserved '
                          '}}</strong><small>/ {{ stats.total }} phòng</small></div><i '
                          'data-lucide="clock-3"></i></article>\n'
                          '  <article class="map-stat maintenance"><div><span>BẢO TRÌ</span><strong>{{ '
                          'stats.maintenance }}</strong><small>/ {{ stats.total }} phòng</small></div><i '
                          'data-lucide="wrench"></i></article>\n'
                          '</section>\n'
                          '<section class="amenity-summary"><span class="amenity-icon"><i '
                          'data-lucide="snowflake"></i></span><div><b>CÓ ĐIỀU HÒA</b><strong>{{ stats.air_conditioned '
                          '}}</strong><small>/ {{ stats.total }} phòng</small></div><div class="without-air"><b>KHÔNG '
                          'CÓ ĐIỀU HÒA</b><strong>{{ stats.without_air_conditioner }}</strong><small>/ {{ stats.total '
                          '}} phòng</small></div></section>\n'
                          '\n'
                          '<section class="building-maps">\n'
                          '{% for card in building_cards %}\n'
                          '  <article class="building-map">\n'
                          '    <header><div class="building-name"><span><i '
                          'data-lucide="building-2"></i></span><div><h2>{{ card.building.name }}</h2><small>{{ '
                          'card.total }} phòng · 5 tầng</small></div></div><div class="building-badges"><b '
                          'class="available">Trống {{ card.counts.available }}</b><b class="occupied">Đang thuê {{ '
                          'card.counts.occupied }}</b><b class="reserved">Đã đặt {{ card.counts.reserved }}</b><b '
                          'class="maintenance">Bảo trì {{ card.counts.maintenance }}</b></div></header>\n'
                          '    <div class="floor-list">\n'
                          '      {% for floor in card.floors %}<div class="floor-row"><div '
                          'class="floor-label"><span>TẦNG</span><strong>{{ floor.number }}</strong></div><div '
                          'class="floor-rooms">{% for room in floor.rooms %}<a href="{% url \'api-room-detail\' '
                          'room.id %}" class="map-room {{ room.status }}" title="{{ room }} — {{ room.monthly_rent|vnd '
                          '}} đ/tháng"><i data-lucide="door-open"></i><strong>{{ room.number }}</strong><small>{{ '
                          'room.get_status_display }}</small>{% if room.has_air_conditioner %}<span class="air"><i '
                          'data-lucide="snowflake"></i></span>{% endif %}</a>{% endfor %}</div></div>{% empty %}<div '
                          'class="map-empty">Không có phòng phù hợp với bộ lọc.</div>{% endfor %}\n'
                          '    </div>\n'
                          '  </article>\n'
                          '{% empty %}<div class="panel map-empty">Không tìm thấy tòa nhà phù hợp.</div>{% endfor %}\n'
                          '</section>\n'
                          '<div class="map-legend"><span><i class="dot available"></i> Phòng trống</span><span><i '
                          'class="dot occupied"></i> Đang thuê</span><span><i class="dot reserved"></i> Đã '
                          'đặt</span><span><i class="dot maintenance"></i> Bảo trì</span></div>\n'
                          '{% endblock %}\n',
 'rentals/tenant_list.html': '{% extends "base.html" %}{% block page_title %}Khách thuê{% endblock %}{% block content '
                             "%}{% with create_url='tenant-create' %}{% include 'rentals/_list_header.html' %}{% "
                             'endwith %}<section class="panel"><div class="list-summary"><span>Danh sách khách '
                             'thuê</span><span>Tổng số: <strong>{{ paginator.count '
                             '}}</strong></span></div><table><thead><tr><th class="row-number">STT</th><th>Họ '
                             'tên</th><th>Điện thoại</th><th>Email</th><th>CCCD/Hộ chiếu</th><th>Trạng '
                             'thái</th></tr></thead><tbody>{% for x in objects %}<tr><td class="row-number">{{ '
                             'page_obj.start_index|add:forloop.counter0 }}</td><td>{{ x.full_name }}</td><td>{{ '
                             'x.phone }}</td><td>{{ x.email|default:"—" }}</td><td>{{ x.identity_number }}</td><td>{{ '
                             'x.is_active|yesno:"Hoạt động,Ngừng" }}</td></tr>{% empty %}<tr><td colspan="6">Chưa có '
                             'dữ liệu.</td></tr>{% endfor %}</tbody></table></section>{% endblock %}\n',
 'tenant/contracts.html': '{% extends "base.html" %}{% block page_title %}Hợp đồng của tôi{% endblock %}{% block '
                          'content %}<section class="panel"><table><thead><tr><th>Mã</th><th>Phòng</th><th>Tòa '
                          'nhà</th><th>Thời hạn</th><th>Tiền thuê</th><th>Trạng thái</th></tr></thead><tbody>{% for x '
                          'in objects %}<tr><td>{{ x.code }}</td><td>{{ x.room.number }}</td><td>{{ '
                          'x.room.building.name }}</td><td>{{ x.start_date|date:"d/m/Y" }} – {{ '
                          'x.end_date|date:"d/m/Y" }}</td><td>{{ x.monthly_rent|vnd }} đ</td><td><span '
                          'class="badge">{{ x.get_status_display }}</span></td></tr>{% empty %}<tr><td colspan="6">Bạn '
                          'chưa có hợp đồng.</td></tr>{% endfor %}</tbody></table></section>{% endblock %}\n',
 'tenant/incident_form.html': '{% extends "base.html" %}{% block page_title %}Gửi yêu cầu hỗ trợ{% endblock %}{% block '
                              'content %}<section class="panel form-panel"><h1>Báo sự cố trong phòng</h1><p '
                              'class="muted">Mô tả rõ tình trạng để bộ phận quản lý xử lý nhanh hơn.</p><form '
                              'method="post">{% csrf_token %}{{ form.as_p }}<div class="actions"><button class="btn '
                              'primary" type="submit">Gửi yêu cầu</button><a class="btn" href="{% url '
                              '\'tenant-incidents\' %}">Hủy</a></div></form></section>{% endblock %}\n',
 'tenant/incidents.html': '{% extends "base.html" %}{% block page_title %}Yêu cầu hỗ trợ{% endblock %}{% block content '
                          '%}<div class="page-actions"><span></span><a class="btn primary" href="{% url '
                          '\'tenant-incident-create\' %}">Gửi yêu cầu mới</a></div><section '
                          'class="panel"><table><thead><tr><th>Ngày gửi</th><th>Phòng</th><th>Nội dung</th><th>Ưu '
                          'tiên</th><th>Trạng thái</th><th>Người xử lý</th></tr></thead><tbody>{% for x in objects '
                          '%}<tr><td>{{ x.created_at|date:"d/m/Y H:i" }}</td><td>{{ x.room.number '
                          '}}</td><td><strong>{{ x.title }}</strong><br><span class="muted">{{ '
                          'x.description|truncatechars:80 }}</span></td><td>{{ x.get_priority_display }}</td><td><span '
                          'class="badge">{{ x.get_status_display }}</span></td><td>{{ x.assigned_to|default:"Chưa phân '
                          'công" }}</td></tr>{% empty %}<tr><td colspan="6">Bạn chưa gửi yêu cầu nào.</td></tr>{% '
                          'endfor %}</tbody></table></section>{% endblock %}\n',
 'tenant/invoice_detail.html': '{% extends "base.html" %}{% block page_title %}Hóa đơn {{ invoice.code }}{% endblock '
                               '%}{% block content %}<section class="panel invoice-sheet"><div '
                               'class="detail-grid"><div><span>Kỳ hóa đơn</span><strong>{{ invoice.period|date:"m/Y" '
                               '}}</strong></div><div><span>Phòng</span><strong>{{ invoice.contract.room '
                               '}}</strong></div><div><span>Ngày phát hành</span><strong>{{ '
                               'invoice.issued_date|date:"d/m/Y" }}</strong></div><div><span>Hạn thanh '
                               'toán</span><strong>{{ invoice.due_date|date:"d/m/Y" }}</strong></div></div><h2>Chi '
                               'tiết</h2><table><thead><tr><th>Nội dung</th><th>Số lượng</th><th>Đơn giá</th><th>Thành '
                               'tiền</th></tr></thead><tbody>{% for x in invoice.items.all %}<tr><td>{{ x.description '
                               '}}</td><td>{{ x.quantity }}</td><td>{{ x.unit_price|vnd }} đ</td><td>{{ x.amount|vnd '
                               '}} đ</td></tr>{% endfor %}</tbody><tfoot><tr><th colspan="3">Tổng cộng</th><th>{{ '
                               'invoice.total_amount|vnd }} đ</th></tr><tr><th colspan="3">Đã thanh toán</th><th>{{ '
                               'invoice.paid_amount|vnd }} đ</th></tr><tr><th colspan="3">Còn nợ</th><th>{{ '
                               'invoice.balance|vnd }} đ</th></tr></tfoot></table><h2>Lịch sử thanh '
                               'toán</h2><table><thead><tr><th>Thời gian</th><th>Số tiền</th><th>Phương '
                               'thức</th><th>Tham chiếu</th></tr></thead><tbody>{% for x in invoice.payments.all %}{% '
                               'if not x.is_void %}<tr><td>{{ x.paid_at|date:"d/m/Y H:i" }}</td><td>{{ x.amount|vnd }} '
                               'đ</td><td>{{ x.get_method_display }}</td><td>{{ x.reference|default:"—" }}</td></tr>{% '
                               'endif %}{% empty %}<tr><td colspan="4">Chưa có thanh toán.</td></tr>{% endfor '
                               '%}</tbody></table></section>{% endblock %}\n',
 'tenant/invoices.html': '{% extends "base.html" %}{% block page_title %}Hóa đơn của tôi{% endblock %}{% block content '
                         '%}<section class="panel"><table><thead><tr><th>Mã hóa '
                         'đơn</th><th>Kỳ</th><th>Phòng</th><th>Tổng tiền</th><th>Đã trả</th><th>Còn nợ</th><th>Trạng '
                         'thái</th></tr></thead><tbody>{% for x in objects %}<tr><td><a href="{% url '
                         '\'tenant-invoice-detail\' x.id %}">{{ x.code }}</a></td><td>{{ x.period|date:"m/Y" '
                         '}}</td><td>{{ x.contract.room.number }}</td><td>{{ x.total_amount|vnd }} đ</td><td>{{ '
                         'x.paid_amount|vnd }} đ</td><td>{{ x.balance|vnd }} đ</td><td><span class="badge">{{ '
                         'x.get_status_display }}</span></td></tr>{% empty %}<tr><td colspan="7">Bạn chưa có hóa '
                         'đơn.</td></tr>{% endfor %}</tbody></table></section>{% endblock %}\n',
 'tenant/notifications.html': '{% extends "base.html" %}{% block page_title %}Thông báo{% endblock %}{% block content '
                              '%}<section class="notification-list">{% for x in objects %}<article class="panel '
                              'notification"><div><h2>{{ x.title }}</h2><p>{{ x.content }}</p></div><time>{{ '
                              'x.created_at|date:"d/m/Y H:i" }}</time></article>{% empty %}<article class="panel">Bạn '
                              'chưa có thông báo.</article>{% endfor %}</section>{% endblock %}\n',
 'tenant/portal.html': '{% extends "base.html" %}\n'
                       '{% block title %}Trang người thuê{% endblock %}\n'
                       '{% block page_title %}Xin chào, {{ tenant.full_name }}{% endblock %}\n'
                       '{% block content %}\n'
                       '<section class="stats-grid">\n'
                       '  <article class="stat info"><span>Phòng hiện tại</span><strong>{% if active_contract %}{{ '
                       'active_contract.room.number }}{% else %}—{% endif %}</strong></article>\n'
                       '  <article class="stat"><span>Tòa nhà</span><strong class="small-value">{% if active_contract '
                       '%}{{ active_contract.room.building.name }}{% else %}Chưa có{% endif %}</strong></article>\n'
                       '  <article class="stat danger"><span>Tổng cần thanh toán</span><strong>{{ total_debt|vnd }} '
                       'đ</strong></article>\n'
                       '  <article class="stat warning"><span>Thông báo chưa đọc</span><strong>{{ unread_count '
                       '}}</strong></article>\n'
                       '</section>\n'
                       '{% if active_contract %}<section class="panel tenant-room"><h2>Thông tin thuê hiện '
                       'tại</h2><div class="detail-grid"><div><span>Mã hợp đồng</span><strong>{{ active_contract.code '
                       '}}</strong></div><div><span>Thời hạn</span><strong>{{ active_contract.start_date|date:"d/m/Y" '
                       '}} – {{ active_contract.end_date|date:"d/m/Y" }}</strong></div><div><span>Giá '
                       'thuê</span><strong>{{ active_contract.monthly_rent|vnd }} đ/tháng</strong></div><div><span>Địa '
                       'chỉ</span><strong>{{ active_contract.room.building.address }}</strong></div></div></section>{% '
                       'endif %}\n'
                       '<section class="two-columns">\n'
                       '  <article class="panel"><div class="panel-heading"><h2>Hóa đơn cần thanh toán</h2><a href="{% '
                       'url \'tenant-invoices\' %}">Xem tất cả</a></div><table><thead><tr><th>Kỳ</th><th>Còn '
                       'nợ</th><th>Hạn trả</th></tr></thead><tbody>{% for x in unpaid_invoices %}<tr><td><a href="{% '
                       'url \'tenant-invoice-detail\' x.id %}">{{ x.period|date:"m/Y" }}</a></td><td>{{ x.balance|vnd '
                       '}} đ</td><td>{{ x.due_date|date:"d/m/Y" }}</td></tr>{% empty %}<tr><td colspan="3">Không có '
                       'hóa đơn cần thanh toán.</td></tr>{% endfor %}</tbody></table></article>\n'
                       '  <article class="panel"><div class="panel-heading"><h2>Yêu cầu gần đây</h2><a class="btn '
                       'primary compact" href="{% url \'tenant-incident-create\' %}">Gửi yêu '
                       'cầu</a></div><table><thead><tr><th>Nội dung</th><th>Trạng thái</th></tr></thead><tbody>{% for '
                       'x in incidents %}<tr><td>{{ x.title }}</td><td><span class="badge">{{ x.get_status_display '
                       '}}</span></td></tr>{% empty %}<tr><td colspan="2">Chưa có yêu cầu.</td></tr>{% endfor '
                       '%}</tbody></table></article>\n'
                       '</section>\n'
                       '{% endblock %}\n'}
